config:
  userName: szymonri
  domain: code.szymonrichert.pl

extraEntrypointScripts:
  01-init-kubeconfig.sh: |
    #!/bin/bash

    mkdir -p "/home/${USER_NAME}/.kube"
    if [[ ! -e "/home/${USER_NAME}/.kube/config" ]]; then
      cp -f /secrets/kube-config.yaml "/home/${USER_NAME}/.kube/config"
    fi

    grep "chmod 0600 /home/${USER_NAME}/.kube/config" "/home/${USER_NAME}/.zshrc" || \
      echo "chmod 0600 /home/${USER_NAME}/.kube/config" >> "/home/${USER_NAME}/.zshrc"

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: code.szymonrichert.pl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: code-tls
      hosts:
        - code.szymonrichert.pl

podAnnotations:
  oauth2-proxy-admission/secret-name: code-server-proxy
  oauth2-proxy-admission/secret-namespace: code-server

podSecurityContext:
  fsGroup: 1000
  # runAsGroup: 1000
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    memory: 512Gi
    cpu: 500m
  requests:
    memory: 128Mi
    cpu: 100m



persistence:
  config:
    enabled: true
    accessMode: ReadWriteMany
    storageClass: nas-nfs
    size: 8Gi
    annotations: {}
  sharedData:
    enabled: true
    accessMode: ReadWriteMany
    storageClass: nas-nfs
    size: 8Gi
    annotations: {}
