defaultRules:
  create: true
  rules:
    alertmanager: false
    etcd: true
    configReloaders: true
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubeControllerManager: true
    kubelet: true
    kubeProxy: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: true
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: false
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true
    windows: true

prometheusOperator:
  manageCrds: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
              - nuc1
              - nuc2
              - nuc3
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - kube-prometheus-stack-operator
        topologyKey: "kubernetes.io/hostname"
  admissionWebhooks:
    patch:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 10m
          memory: 100Mi
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 32Mi
    
  prometheusConfigReloader:
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 200Mi

grafana:
  assertNoLeakedSecrets: false
  deploymentStrategy:
    type: Recreate
  priorityClassName: system-cluster-critical
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: false
    runAsUser: 1000
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
              - nuc1
              - nuc2
              - nuc3
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - grafana
        topologyKey: "kubernetes.io/hostname"
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 384Mi
  persistence:
    type: pvc
    enabled: true
    storageClassName: nas-nfs
    accessModes:
      - ReadWriteOnce
    size: 2Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    hosts:
      - grafana.szymonrichert.pl
    path: /
    tls:
      - hosts:
        - grafana.szymonrichert.pl
        secretName: grafana-tls
  grafana.ini:
    auth:
      disable_login_form: true
    "auth.generic_oauth":
      enabled: true
      auto_login: true
      scopes: openid,profile,email,offline_access,groups
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: full_name
      name: Keycloak
      allow_sign_up: true
      auth_url: https://auth.szymonrichert.pl/realms/master/protocol/openid-connect/auth
      token_url: https://auth.szymonrichert.pl/realms/master/protocol/openid-connect/token
      api_url: https://auth.szymonrichert.pl/realms/master/protocol/openid-connect/userinfo
      role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-dev') && 'Editor' || 'Viewer'
      allow_assign_grafana_admin: true
    server:
      root_url: https://grafana.szymonrichert.pl/
    smtp:
      enabled: true
      host: "email-smtp.eu-central-1.amazonaws.com:465"
      from_address: "monitoring@szymonrichert.pl"
    database:
      type: postgres
      host: grafana-postgresql:5432
      user: grafana
      password: "${POSTGRESQL_PASSWORD}"
      ssl_mode: require
  envValueFrom:
    POSTGRESQL_PASSWORD:
      secretKeyRef:
        name: grafana.grafana-postgresql.credentials.postgresql.acid.zalan.do
        key: password
prometheus:
  service:
    sessionAffinity: "ClientIP"
  prometheusSpec:
    priorityClassName: system-cluster-critical
    replicas: 3
    ruleSelector: {}
    ruleNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    retentionSize: 100GB
    resources:
      limits:
        cpu: 500m
        memory: 3000Mi
      requests:
        cpu: 300m
        memory: 1536Mi
    storageSpec:
      volumeClaimTemplate:    
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: local-path
          resources:
            requests:
              storage: 100Gi
    additionalScrapeConfigs:
      - job_name: nas
        metrics_path: /metrics
        static_configs:
          - targets:
            - 192.168.1.32:9100

prometheus-node-exporter:
  hostNetwork: false

alertmanager:
  enabled: false
