grafana:
    adminUser: ENC[AES256_GCM,data:LnLmtjdd3g==,iv:YY6R6RoKljbo91a/DkA9Rli5deOA/tUxhy1AAV0U534=,tag:+8vz60DEGzcOZ7v/OHsqmQ==,type:str]
    adminPassword: ENC[AES256_GCM,data:CsSOapEksy/7wYtXmevjhu0=,iv:ZXh5+vZ+6M3d0SPYObBRYjaLvoCTLXw3Zu8Pg7L0oAg=,tag:jXq9ra0IXZaV3W9OW1RKVg==,type:str]
    grafana.ini:
        smtp:
            user: ENC[AES256_GCM,data:R/wlv6UBtWDarO4sEImLC79HTiANGw==,iv:BN1dOpqo8lmgrFZ8Dd6bT9yhwAvoqXKstglol4oh5Js=,tag:McGSSiwEuk8ETIwtRzdfcA==,type:str]
            password: ENC[AES256_GCM,data:0XxzdkChVeE=,iv:ffotwJrZezvcmHqNlqT+acSRp6ojJ4SONH5DHcnT/Nk=,tag:nLugBDcplffIimzCxhZWAA==,type:str]
        auth.generic_oauth:
            client_id: ENC[AES256_GCM,data:vmd4YO2Hpg==,iv:+WhIlsruKY7MnRodyWPalmbDI2tOrrcKwHSCpFUUcaA=,tag:THzEpXG4YyZnXPGbYaELew==,type:str]
            client_secret: ENC[AES256_GCM,data:rljZScUy/PQinT6HXap5HL7vI24UnBJI6wiwyRs6MGk=,iv:6jghpwzUOEPYLAN5xIKLgeBXR163A/5akyUDpOvRaK0=,tag:b+ZqEYZ9HJ1vTCKjpdF8Ag==,type:str]
alertmanager:
    config:
        global:
            smtp_auth_username: ENC[AES256_GCM,data:lLQ4RQEZeSE+5yioP7Nn8lsY/ME+uA==,iv:KxjSeNKTkxZpV8FaJelG8sEdlS3S6mkOPukBCaeqF0o=,tag:SjB9knn4aVBb+2SuS5hgzQ==,type:str]
            smtp_auth_password: ENC[AES256_GCM,data:p835XfrTfBE=,iv:QQq6i5aaOgnwV3inpeIBuQAmwUj9veCz+nNe3Q6dU3I=,tag:+6oNAIr8tme//sDPJNjhGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-19T09:47:19Z"
    mac: ENC[AES256_GCM,data:XmT3H6r0nhXgy3KoVV2qw7mCnwdYqlLqKB3SXAGpcRziqfJC5JPd3WH2P0fMonGNGhKWly+FVbgVgJafWgeMuZexgIEhU+vfJJZ5DDikNeWJCd9laCrdi+3MDEab9z98jUH8kSlwjtEt25wh6hzh++o1yl4DuqPlC467udcinwo=,iv:zqKMYmxkIxiUvYYVlR3XJosGmyLQQ8FzYg+EXmyAl9g=,tag:LecsCJ6PEmSuHw734ppQaA==,type:str]
    pgp:
        - created_at: "2023-05-19T09:47:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTAQ/+JzLbCot4CDmTGjD7B40CkBIXWdTaK/p3KL9Oej1aZEFa
            rnPXfIf7Q56b8cS47FupjKSq0rdXly3TGgbIelGciCDaBBulcJmYp0rOx/O1471D
            dFkt7UKAfC5LLZAhG49mppfzeF+jepo138fjkX3uzRxKLZnvvbyzgcs4bpL8GIJE
            AbQ/jioBVwCHZE/9UpKPf/ECQYqJN+cDlRBbtw3NbAU1KlPSlhW8CKx/eFOMPd5Q
            uO2n/OQUKtBQ5jSeTYVJ+flDMDyhimj9miMvlTT2J5qtEITfwe0u2cIzIFeON9u+
            cligwJ/bDE4zqLXyq1qbKywDqC2xUjxIZXkSNKHwtJiNg7P8IqsilRGi+KjywBDl
            UkEwZv6MHjs3BjTACjRNTTNTLYzrkDKg9TWr0GPPu4DwyryWzBz8HmzZnvk56i5+
            DctdW1If+WjHXeVIFvAqctz3iFGPg6vkVJ85Jw3dG1Q2tPrRRjY/ZEVhMoNTv6rS
            GLcC38BjBVAHm4rSOmyYA41BfD6bb6U9h8WYR5D+IDtdBY914jSvZYAx3U/HrZX+
            ypwCzmJJ8dZTrBw5JEJJhlNQWiVbeim4TThhra1j+Po+w1U1ZY/bcL9rUC3RE+eY
            eBYMgaHAEI7whSxsCm+nZQaMDWKWzM8zST4LKLFb6c44VWQOMSO8l/3zjNqV2F7S
            XgFt94Xl+LLsY0z1DtR18dhq9Q8d6jtOQMZmzi4SU7dvT5uVCCurrkCc8/0T7K9g
            CmqejjlCUEydj76pKz/QkUqe3hOQaMf/jRBBVJUBM8n6ppRw6caiz0bvn+Zmjjk=
            =oyfA
            -----END PGP MESSAGE-----
          fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.7.3
