grafana:
    adminUser: ENC[AES256_GCM,data:bRIeN5s1Ng==,iv:yAqfa9gRdc0L23fP9DGyNXicK7dS8FCMhzZ2mrMyIVM=,tag:19ZIhAX9DiOI/di+KtymVg==,type:str]
    adminPassword: ENC[AES256_GCM,data:ki7vYPoR2JQgcKskVl6IhkU=,iv:Md0mKpbmKYO+Rq6XHEiuEsT+/8aUrL5i3cdRN9LEqig=,tag:k1olbYX67EOrxm91Il1N/A==,type:str]
    grafana.ini:
        smtp:
            user: ENC[AES256_GCM,data:72rTBhuQGknc9qxEaPZxXgfzf5M=,iv:2DOaKip1zTTSXR9V1LJod1Q/ZqU0AgO/Gu38Xbw72pc=,tag:8QDW1By5aA8rVc7dD3hqJw==,type:str]
            password: ENC[AES256_GCM,data:zWwx4LMgyDa0BtJQ7/B2w2nxyglljvdwFa4Cf0QiKQ9NuEfjovdyXcmTzc0=,iv:R3WsQATzUPBg2VKcUebsjC8vTxdLEuHFefWKIvrMxXE=,tag:tAv9JlIfQJD705ARh2PPyg==,type:str]
        auth.generic_oauth:
            client_id: ENC[AES256_GCM,data:AYkMjtTQoQ==,iv:ABHtwPy4F2gk5rPp1rU4wGk8MawNgEDk8spjxIrz9qE=,tag:MsaOFMaaDIDecE/gZ+TFyw==,type:str]
            client_secret: ENC[AES256_GCM,data:lVOB8Utz1RLchCsGCAkrV7aOBttoNJb8iLPjSjZ5FwA=,iv:VncdgkHvjuRUFbfOYszM1xHaInxCX7Ddy0bjK9uU8u4=,tag:AdDtyNVoT+mk0fDr4oL1dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-06T12:20:01Z"
    mac: ENC[AES256_GCM,data:LeTz5/5Q6z//XGErC/uTb6e169+nQ6e7BibDr3XBIzuaBwPnyC6valsQVpo6fsgtWs589Jq2weug+tU2QwI7o6qyuF0yttO5AmV8qWhA44y0xKPEXBpuS9u97tO4AA7ADYp9C9HIHr0yVF8CEbbP3x8IqgS6YJOy0Oh5Gy9x9ek=,iv:KJSI499d9VKrh7lrHtLa4bE10du7jS98j8FTHk9w95I=,tag:2SqabYQZ0F8KRrROSXmwGQ==,type:str]
    pgp:
        - created_at: "2024-02-06T12:20:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTARAAgaBKgObB04Nl9XNw/RCmV5SPkqMG3kJGrfxOCaWZE3ef
            Q1RAljWAOrZ8ldBPDqJQjM3aWxZcOnZWeG4AwsDvfolV+BK8g3DBleWeueMFYyDE
            OhfgNDFRx9zgmTEHkx2BbNXpxVkxy6Co79AEYHj4mGml+8LBASr8R9bDxJCrCjsB
            CbrTY23iOKN6jo93cTQq5mI87ZwTm57dhJG9Qt7uPBCC2J0oD/n+i94fcdubDRCB
            jazpA3GFHl66ufJWIvkyUw93HyKfIV2d+h+GRUSzHlPS01dAuNYnNHzfHp/apS8u
            S36jqnW4bnSzNRIn1Cc5s2oKMb/dTyUbh5RLwcTPDfd5U1mxZZ418Uc0PcXpKFZP
            nX2QbM/wInDK1QGnKkwtDb9Zkr9h9LEcsbOB9qvHKDS+5DcvwXDg26EM/T4ZVLlP
            zJEHaxcojkDjRN1dHsX1e8ZPdG98Q7QuVtKcUHsPIpUT0W0HC0FOtd3HNF4F27jx
            1UnJ5fvT0XLq2Ci8m29X7PzHAnhExSxNcTAFLJktdjh5/VDWVrrQdyfdo6TXCw3k
            z5SDTxEuWynKGLSZkiTVr9sT3YYWtiCnPl7pShj7klHaWV6UxaK9GU4ZW8+iAGA8
            Wkbw/D3Et034EhatJ3ayggIFDzb0Ngww3U+sJgvvkQKYMEYHqXFIEnBDpV3GS9HS
            XgHug6sscfGKkHLjyxeBDQfCpyn5yHBqymPL/ttjEiVoJM0szXddBiQ8aF840n9g
            +3ThO7vcOduo85ZaWpmeNScvTP0H6no/sT0dL8mGow3ssq84d+b0SYdar3e69Zc=
            =lnr2
            -----END PGP MESSAGE-----
          fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.7.3
