repositories:
- name: szymonrychu
  url: https://raw.githubusercontent.com/szymonrychu/charts/master/
templates:
  operators-default:
    disableValidation: true
    disableValidationOnInstall: true
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Environment.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml

releases:

- name: gha-runner
  version: 2.293.14
  chart: szymonrychu/gha-runner
  namespace: gha-runner
  labels:
    purpose: cicd
    application: gha-runner
  <<: *default
  wait: false
