backups:
    s3:
        accessKey: ENC[AES256_GCM,data:aqhX3GLqJvTzJJvJu8eKf+KFUFI=,iv:4dCosTwxiJKNMdtnyU94yeA0we3Ph05lMMctzGlC0Aw=,tag:MDpxTdOQJ6usGMcH7lrCow==,type:str]
        secretKey: ENC[AES256_GCM,data:C54Ls+1Yo5X7ku7w/Q60OMBHRZMgy7cQL12bfTUSUxGwei1xxKotfA==,iv:waABeyf0YuA/AFU0MUF/xmwlztFYeydRn0Yga9V+Dos=,tag:vLtSns1FgJddZJhbeGX0tA==,type:str]
recovery:
    s3:
        accessKey: ENC[AES256_GCM,data:Djj5gqPh5nyBsv35W4nZiB8wauk=,iv:KorWOLzY7N3h90hNqneWIqqC3GgHWJTYfNYHl/Pbcfc=,tag:Y4MfM4hlVDrqlQqRN9rrlg==,type:str]
        secretKey: ENC[AES256_GCM,data:GUE4IyeOTTLuveBsb705zN/VRBB96Fcjgl0PC6E4l/mHauB75Jd1cg==,iv:W2D6/cz1jaaFspzK2cgFh3hKoGfH2pC0ujB16H14odM=,tag:fiACuuRaTPN21LcPvR0sKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-23T16:04:07Z"
    mac: ENC[AES256_GCM,data:8h5SDwBKQWu7CZslwXcznyM73G76nPSwECffCDAphIQmLBV3axmwQ+SaKxlCY7Qs11yoArr5Oq6J13O+zx9fYOSMeGqObPm2FP5CQvMI3sxygLVfQG6c3CxOiSlRGqmIRwRO4LICCEFUNls7LORXTDxiBbxd63tpKEJABzc16a8=,iv:OHYmrlYd75GctROXGkjcKrgHiL/keOAETFgoOQNdhg8=,tag:P9giAj1+xwt75JrkfaxdqQ==,type:str]
    pgp:
        - created_at: "2024-12-23T16:04:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTAQ/+MFoPqm6LGNVE05AnkNg8PN+y349BQ0Vay4kPoKnLhjAG
            Bt3mvhbeSl2cfu43WDziTuTSEQR/9cJVPhmeYQoiU3j3cGpq4p5JaL/PacWcnFUv
            4bxtTjKNTHgFe3DSsbibrPeoIT6wzlx6odv1BwcRqA88jEJ458VGoDqYYy9+qRfm
            prgQFtYX9GfBYxbH136Ic8TMv9Ip4r26JqCkT4VNCrkZO2K7RuJ3lQuFmI6diVmO
            0TGoe3uhIOWvoI03KSqLSm492kREH/lVXbPBHRCN/H/elAYFWfVQ3/dRR53Y7ZwC
            OahWwwfcDCbjvZIe/DmnUyTlymcmBVFvRajmji01ScVm2gGr5CFSvIEEwATddfBJ
            hXVZJeDhRrhOC0GdaKOvCHOe8eJ4u354wV/6FLZl/XYZ08HdyGc/mYENc7yCnK+V
            u/aFAMvZx8Hvvj/mX+0wab6w0wigAKOX1w/mdquTBs+WwewzbAfqebkjTfbwaus9
            2eqbL1Ss4yHkNzUxDlJF8iBgGaW7Ds93moJKIlU+/iLzIan/jiinMGSKmkeffmvr
            J3J+syzCyjTj9brXjDuh67ExSotAVhO2+F23xnPrq1zOjkGZa7d3JLaoSkjQ/iw3
            EisibWHUrkB3D18XvYZ+1agt/5VjMpRm7ybqtg2bwhhel9J1tnnVnjSujxRds9DS
            XgEkISH/r6ZkdC7X+zjoiguqa8BQjNTn24s3fim0Rytwq9bd5cxdjgmi1OLAzqTw
            yqtw51EDu48KORJGNGI+zJ6vFrOVgW1OUtLhulGkdHBedcJahUnQGOyRg0cwd6Y=
            =q3Qi
            -----END PGP MESSAGE-----
          fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.9.1
