kind: ENC[AES256_GCM,data:iaayrHVi,iv:BSyXDdGPw2JB0rS2LNmfdA+4Kg4kYdHm9uMpfDB5D2Y=,tag:tmvjGPWaejyn4KLyVda3Fw==,type:str]
apiVersion: ENC[AES256_GCM,data:+DM=,iv:uC+tDAlMUiwmpmcfj5WJt0IgVULXAj6AWpYZClpTumk=,tag:/qQBwydT2+bfQRh4ahnzAw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JYyaxSiPlow=,iv:7pWhqSD7dLCGm+tmzcs6F2FiOm4jl6nNu9TlC4J0Rv8=,tag:RUdKWv1ZJTtwcap6CoJmcg==,type:str]
    namespace: ENC[AES256_GCM,data:fhj8CfDkmy//Xy8=,iv:SSDQCppbWvWFZIsJRdUxiNyYkF3qK9XCKKu/8p7ongw=,tag:p5A6PtPbIJ+VPGejMykT3Q==,type:str]
type: ENC[AES256_GCM,data:eZkBqhyP,iv:PyOiAoSDn961/4Hz1dUb7qvSYDN7Y4dbeQPXwXmZALI=,tag:w8PHZLTCqFtt7XHlyWWlIQ==,type:str]
data:
    password: ENC[AES256_GCM,data:VkUdq0zRL0Tr5t77/hRthtLVsP9w3s/C+yhxva2cXwxX6e1l53yeXekSM0k=,iv:8D9025eOI7jfeS2aoKxpaDICcVZw0pWEpSKnMwL7xQU=,tag:qK1548tVEIiD+5814k8uKQ==,type:str]
    username: ENC[AES256_GCM,data:IToqTu2X5xk=,iv:YhxSQFX7teYvLmvPy7O/Tt3kcrGZCREqeGHLt/BtGbs=,tag:hKZsXPaOFkXpBQsR7t54ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-23T08:45:12Z"
    mac: ENC[AES256_GCM,data:Bk1rI9xgEFhrT4PoJZqdgHf8dhNavv7bVmFn/DAbGnM60VcCw3Pui0BjyKXmHW2aVVmsp+PqrtQfF+NqQqNUo2WluzOaL/YxH5i9K7gMam20K9cdSOo3Fl9ESHdcxeqvAQig+ftp6KoBFvjaDqXHJpzOAsctiHNMydhGV3qh/v4=,iv:7NIMaWZtdDgHAPUlSrrbtFvY78FtQUYzWCFBsRva8sI=,tag:ddbJ7sOQW7mWMTn3wenj1g==,type:str]
    pgp:
        - created_at: "2023-01-23T08:45:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTAQ/+PVrRTgxO/BnRuFMTl0WvH29c9FV7bQik1p/a2tz5kEnI
            +N0OcVPDkcFaybcbX3ips/uQEI1IQi7jDCaVwjugqisGWD4goXt4CCC7SEFqa1m9
            jLm3gBp7npdg8DmLoDc0j/0S4G60zM4Lml+pWCtDH37Zcvx7/J7cG3tvbTLp+/Fy
            afw6LXBbw+ADC0QzRPcX4b73PI7ZyGj9wXCTMhhHP369Yw6B/pRL1MNG1nxFnULa
            iretxihTuZTBEmhoBZqhycrE8GIe8eANW657h8JnFvvmLgWaq8SoI/EQUYnkNlCS
            jg/e9IdErXdAEonUptuvsnJPTYvIz4yfzmDpqvnVyvPcNjqDomSnioAy6Eojgjjh
            xrMAzA/fogrZVgC/f7MBjnJiVpTxO7+5S7V2BWCBie9GBLAMS4DzH7nDfQWcyK/M
            0IvLcerNay5R9BuzQpM/6clkV6qwEdySkwlFO/9eLJys1wdDMHrr2yzvYNVRreF2
            YeeeKh86f+ZEEfxToiJppRLS8i63fsAFD6yd2K+Sn0zjmDOdmRRrGTw2XlSqE8LH
            ks5KrZ2NlnKjR8s3KxvrUD6XJTwN7cYOtiO3+qRSxlxOMP0f7F+ACwBTFCfgKx/5
            lo0HRqpOR/1b8sBn4lHwJIHUgAD4V9790wWR1eMPME+kVFmmuoXCv8IhcYwBrabS
            XgH254MU5W/pC1rtBIJKo+LUSInd7MFVGdO7xwtkFDGm4HceIMqs+P+8mkmbGWt6
            Q2u9gpFQa7WzAW9MxUq5isOWFrQ+U4nNm0Z6BD4OzyRDA5duCCqYOxfAwI3hOMk=
            =4jXd
            -----END PGP MESSAGE-----
          fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.7.3
