---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-tvshows
provisioner: smb.csi.k8s.io
parameters:
  source: "//samba.samba.svc.cluster.local/tvshows"
  csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  csi.storage.k8s.io/provisioner-secret-namespace: "kube-system"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "kube-system"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino
  - vers=3.0
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-movies
provisioner: smb.csi.k8s.io
parameters:
  source: "//samba.samba.svc.cluster.local/movies"
  csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  csi.storage.k8s.io/provisioner-secret-namespace: "kube-system"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "kube-system"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino
  - vers=3.0