repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: szymonrychu
  url: https://szymonrychu.github.io/selfhosted-kubernetes-charts
- name: nfs-subdir-external-provisioner
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
- name: rook-release
  url: https://charts.rook.io/release
templates:
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - storage
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml
  operators-default:
    disableValidation: true
    disableValidationOnInstall: true
    <<: *default
releases:

- name: local-path-provisioner
  chart: szymonrychu/local-path-provisioner
  namespace: storage-system
  version: 0.0.24
  labels:
    purpose: storage
    application: local-path-provisioner
  <<: *default

- name: nfs-subdir-external-provisioner
  chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
  namespace: storage-system
  version: 4.0.18
  labels:
    purpose: nfs
    application: nfs-subdir-external-provisioner
  <<: *default

- name: snapshot-controller
  chart: szymonrychu/snapshot-controller
  namespace: storage-system
  version: 2.0.4
  labels:
    purpose: storage
    application: snapshot-controller
  <<: *default

- name: rook-ceph
  chart: rook-release/rook-ceph
  namespace: rook-ceph
  version: v1.13.5
  needs:
  - storage-system/snapshot-controller
  labels:
    purpose: storage
    application: rook-ceph
  <<: *default

- name: rook-ceph-cluster
  chart: rook-release/rook-ceph-cluster
  namespace: rook-ceph
  version: v1.13.4
  needs:
  - storage-system/snapshot-controller
  - rook-ceph/rook-ceph
  labels:
    purpose: storage
    application: rook-ceph
  <<: *default
