repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: jetstack
  url: https://charts.jetstack.io
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: metallb
  url: https://metallb.github.io/metallb
templates:
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - ingress
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml
  operators-default: &operators
    disableValidation: true
    disableValidationOnInstall: true
    <<: *default
releases:

- name: metallb
  chart: metallb/metallb
  namespace: ingress-system
  version: 0.14.8
  labels:
    purpose: backbone
    application: metallb
  <<: *default

- name: cert-manager
  chart: jetstack/cert-manager
  namespace: ingress-system
  version: v1.16.0
  labels:
    purpose: backbone
    application: cert-manager
  <<: *operators

- name: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  namespace: ingress-system
  version: 4.11.2
  needs:
  - ingress-system/metallb
  - ingress-system/cert-manager
  labels:
    purpose: backbone
    application: ingress-nginx
  <<: *default

- name: external-dns
  chart: bitnami/external-dns
  version: 8.3.9
  namespace: ingress-system
  needs:
  - ingress-system/ingress-nginx
  labels:
    purpose: backbone
    application: external-dns
  <<: *default
