ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: lidarr.szymonrichert.pl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: lidarr-tls
      hosts:
        - lidarr.szymonrichert.pl

podAnnotations:
  oauth2-proxy-admission/secret-name: lidarr-proxy
  oauth2-proxy-admission/secret-namespace: media

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nas
          operator: In
          values:
          - "true"

resources:
  limits:
    cpu: "2"
    memory: 1024Mi
  requests:
    cpu: 50m
    memory: 128Mi

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /var/lib/lidarr
  media:
    enabled: true
    type: hostPath
    hostPath: /samba
