---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    prometheus: mon
spec:
  namespaceSelector:
    matchNames:
    - server-monitoring
  selector:
    matchLabels:
      k8s-app: node-exporter
  endpoints:
  - port: metrics
    interval: 10s
---
apiVersion: v1
kind: Service
metadata:
  name: nas-local
  namespace: monitoring
  labels:
    k8s-app: node-exporter
spec:
  type: ExternalName
  externalName: 192.168.1.32
  clusterIP: ""
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nas-local
  namespace: monitoring
  labels:
    k8s-app: node-exporter
subsets:
  - addresses:
    - ip: 192.168.1.32
    ports:
      - name: metrics
        port: 9100
        protocol: TCP
