{
 "title": "NAS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "nas_ip", "query": "192.168.1.72" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{mode=~\"idle|iowait|steal\", instance=\"${nas_ip}:9100\"}[$__rate_interval])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{mode=\"idle\", instance=\"${nas_ip}:9100\"})\n)\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(node_load1{instance=\"${nas_ip}:9100\"}[$__rate_interval])",
     "legendFormat": "1m load average"
    },
    {
     "expr": "avg_over_time(node_load5{instance=\"${nas_ip}:9100\"}[$__rate_interval])",
     "legendFormat": "5m load average"
    },
    {
     "expr": "avg_over_time(node_load15{instance=\"${nas_ip}:9100\"}[$__rate_interval])",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=\"${nas_ip}:9100\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  avg_over_time(node_memory_MemTotal_bytes{instance=\"${nas_ip}:9100\"}[$__rate_interval])\n-\n  avg_over_time(node_memory_MemFree_bytes{instance=\"${nas_ip}:9100\"}[$__rate_interval])\n-\n  avg_over_time(node_memory_Buffers_bytes{instance=\"${nas_ip}:9100\"}[$__rate_interval])\n-\n  avg_over_time(node_memory_Cached_bytes{instance=\"${nas_ip}:9100\"}[$__rate_interval])\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "avg_over_time(node_memory_Buffers_bytes{instance=\"${nas_ip}:9100\"}[$__rate_interval])",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "avg_over_time(node_memory_Cached_bytes{instance=\"${nas_ip}:9100\"}[$__rate_interval])",
     "legendFormat": "memory cached"
    },
    {
     "expr": "avg_over_time(node_memory_MemFree_bytes{instance=\"${nas_ip}:9100\"}[$__rate_interval])",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{instance=\"${nas_ip}:9100\"}) /\n  avg(node_memory_MemTotal_bytes{instance=\"${nas_ip}:9100\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"${nas_ip}:9100\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"${nas_ip}:9100\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"${nas_ip}:9100\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{instance=\"${nas_ip}:9100\", fstype!=\"\", mountpoint!=\"\", mountpoint!~\"/run.*\", mountpoint!~\"/boot.*\"})\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{instance=\"${nas_ip}:9100\", fstype!=\"\", mountpoint!=\"\", mountpoint!~\"/run.*\", mountpoint!~\"/boot.*\"})\n"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Received",
     "type": "timeseries",
     "description": "Network received (bits/s)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"${nas_ip}:9100\", device!=\"lo\"}[$__rate_interval]) * 8",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Network Transmitted",
     "type": "timeseries",
     "description": "Network transmitted (bits/s)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"${nas_ip}:9100\", device!=\"lo\"}[$__rate_interval]) * 8",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Gpu Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(DCGM_FI_DEV_GPU_TEMP{instance=\"${nas_ip}:9400\"}[$__rate_interval])) by (gpu)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(DCGM_FI_DEV_SM_CLOCK{instance=\"${nas_ip}:9400\"}[$__rate_interval])) by (gpu)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(DCGM_FI_DEV_GPU_UTIL{instance=\"${nas_ip}:9400\"}[$__rate_interval])) by (gpu)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(DCGM_FI_DEV_FB_USED{instance=\"${nas_ip}:9400\"}[$__rate_interval])) by (gpu)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}