apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: grafana-postgresql
#  labels:
#    application: test-app
#    environment: demo
#  annotations:
#    "acid.zalan.do/controller": "second-operator"
#    "delete-date": "2020-08-31"  # can only be deleted on that day if "delete-date "key is configured
#    "delete-clustername": "acid-test-cluster"  # can only be deleted when name matches if "delete-clustername" key is configured
spec:
  dockerImage: ghcr.io/zalando/spilo-15:3.0-p1
  teamId: "grafana"
  numberOfInstances: 1
  podPriorityClassName: system-cluster-critical
  users:  # Application/Robot users
    superuser:
    - superuser
    - createdb
    grafana: []
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  enableConnectionPooler: false # enable/disable connection pooler deployment
  enableReplicaConnectionPooler: false # set to enable connectionPooler for replica service
  allowedSourceRanges: [] # load balancers' source ranges for both master and replica services
  databases:
    grafana: grafana
  postgresql:
    version: "15"
    parameters:  # Expert section
      shared_buffers: "32MB"
      max_connections: "60"
      log_statement: "all"
#  env:
#  - name: wal_s3_bucket
#    value: my-custom-bucket

  volume:
    size: 50Gi
    storageClass: ceph

  enableShmVolume: true
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi

  enableLogicalBackup: true

  maintenanceWindows:
    - 01:00-06:00  #UTC
    - Sat:00:00-04:00
  # tls:
  #   secretName: grafana-postgresql-ssl
  #   certificateFile: "tls.crt"
  #   privateKeyFile: "tls.key"
