{
 "title": "SMARTCTL",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"node-exporter\", sysname!=\"darwin\"},nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(smartctl_device_temperature{nodename=~\"$nodename\"}[$__rate_interval])",
     "legendFormat": "{{nodename}}/{{device}}"
    }
   ]
  },
  {
   "title": "Error log count",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(smartctl_device_error_log_count{nodename=~\"$nodename\"}) by (nodename, device)",
     "legendFormat": "{{nodename}}/{{device}}"
    }
   ]
  },
  {
   "title": "Powercycle count",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(smartctl_device_power_cycle_count{nodename=~\"$nodename\"}) by (nodename, device)",
     "legendFormat": "{{nodename}}/{{device}}"
    }
   ]
  },
  {
   "title": "Smartctl status",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(smartctl_device_smart_status{nodename=~\"$nodename\"}) by (nodename, device)",
     "legendFormat": "{{nodename}}/{{device}}"
    }
   ]
  },
  {
   "title": "IO",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 18, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg_over_time(node_disk_io_now{nodename=~\"$nodename\"}[$__rate_interval])",
     "legendFormat": "{{nodename}}/{{device}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(smartctl_device_power_on_seconds{nodename=~\"$nodename\"}) by (nodename, device) / 60 / 60 / 24 ",
     "legendFormat": "{{nodename}}/{{device}}"
    }
   ]
  }
 ]
}