ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: flood.szymonrichert.pl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: flood-tls
      hosts:
        - flood.szymonrichert.pl

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  # runAsNonRoot: true
  runAsUser: 1000

flood:
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
rtorrent:
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

oauth2proxy:
  config:
    clientId: flood
    redirectUrl: https://flood.szymonrichert.pl/oauth2/callback
    realmUrl: https://auth.szymonrichert.pl/realms/master
    cookieName: oauth2-authorization-cookie
    cookieDomain: flood.szymonrichert.pl

persistence:
  config:
    enabled: true
    storageClass: nas-nfs
    type: pvc
    size: 10Gi
  data:
    enabled: true
    storageClass: nas-nfs
    type: pvc
    size: 10Gi
  media:
    enabled: true
    type: hostPath
    hostPath: /samba

