repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: szymonrychu
  url: https://szymonrychu.github.io/charts
environments:
  lab: {}
templates:
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Environment.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml

releases:

# - name: speedtest-exporter
#   chart: k8s-at-home/speedtest-exporter
#   version: 5.3.3
#   namespace: monitoring
#   labels:
#     purpose: monitoring
#     application: speedtest-exporter
#   <<: *default

# - name: esphome
#   chart: truecharts/esphome
#   version: 11.0.53
#   namespace: esphome
#   labels:
#     purpose: home-automation
#     application: esphome
#   <<: *default

- name: home-assistant
  chart: szymonrychu/home-assistant
  version: 0.4.0
  namespace: home-assistant
  labels:
    purpose: home-automation
    application: home-assistant
  <<: *default