repositories:
- name: szymonrychu
  url: https://szymonrychu.github.io/selfhosted-kubernetes-charts
environments:
  lab: {}
templates:
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 1200
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - home-automation
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml

releases:
- name: eclipse-mosquitto
  chart: szymonrychu/eclipse-mosquitto
  version: 0.1.4
  namespace: home-automation
  labels:
    purpose: home-automation
    application: eclipse-mosquitto
  <<: *default

- name: esphome
  chart: szymonrychu/esphome
  version: 3.0.10
  namespace: home-automation
  labels:
    purpose: home-automation
    application: esphome
  <<: *default

- name: home-assistant-database
  chart: cnpg/cluster
  namespace: home-automation
  version: 0.0.3
  force: true
  labels:
    purpose: home-automation
    application: home-assistant-database
  <<: *default

- name: home-assistant
  chart: szymonrychu/home-assistant
  version: 0.11.12
  namespace: home-automation
  needs:
  - home-automation/home-assistant-database
  labels:
    purpose: home-automation
    application: home-assistant
  <<: *default
