repositories:
- name: szymonrychu
  url: https://szymonrychu.github.io/selfhosted-kubernetes-charts
environments:
  lab: {}
templates:
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 1200
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - home-automation
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml

releases:

- name: esphome
  chart: szymonrychu/esphome
  version: 1.2.8
  namespace: home-automation
  labels:
    purpose: home-automation
    application: esphome
  <<: *default

- name: home-assistant
  chart: szymonrychu/home-assistant
  version: 0.10.7
  namespace: home-automation
  labels:
    purpose: home-automation
    application: home-assistant
  <<: *default
