repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: szymonrychu
  url: https://szymonrychu.github.io/charts
- name: node-red
  url: https://schwarzit.github.io/node-red-chart/
environments:
  lab: {}
templates:
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - home-automation
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml

releases:

- name: esphome
  chart: szymonrychu/esphome
  version: 1.1.0
  namespace: home-assistant
  labels:
    purpose: home-automation
    application: esphome
  <<: *default

- name: home-assistant
  chart: szymonrychu/home-assistant
  version: 0.7.0
  namespace: home-assistant
  labels:
    purpose: home-automation
    application: home-assistant
  <<: *default

# - name: node-red
#   chart: node-red/node-red
#   version: 0.26.0
#   namespace: home-assistant
#   labels:
#     purpose: home-automation
#     application: node-red
#   <<: *default
