environments:
  lab: {}
templates:
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 1200
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - home-automation
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml

releases:

- name: esphome
  chart: oci://ghcr.io/szymonrychu/helm-charts/esphome
  version: 3.0.26
  namespace: home-automation
  labels:
    purpose: home-automation
    application: esphome
  <<: *default

- name: home-assistant-database
  chart: cnpg/cluster
  namespace: home-automation
  version: 0.1.3
  force: true
  labels:
    purpose: home-automation
    application: home-assistant-database
  <<: *default

- name: home-assistant
  chart: oci://ghcr.io/szymonrychu/helm-charts/home-assistant
  version: 0.11.34
  namespace: home-automation
  needs:
  - home-automation/home-assistant-database
  labels:
    purpose: home-automation
    application: home-assistant
  <<: *default
