auth:
    adminUser: ENC[AES256_GCM,data:66doDAOj+nJiyMqi5zNG84+EdRl3yw==,iv:c63IbXfdtEqpeQuuEB8NEADnlrmumz/DNkyd1TkSt/U=,tag:OS5K8uDE8FXDCW9AH5wHzQ==,type:str]
    adminPassword: ENC[AES256_GCM,data:x6+DzcYEVMGOvplSjwNM1Es=,iv:jYiSJkn8AyA0VJTOt0oUZhEMaoKu+VIAvzaT+hWiPsU=,tag:8BNS2RjZ5TF9l9+9dl+pew==,type:str]
global:
    postgresql:
        auth:
            password: ENC[AES256_GCM,data:i5y/pvwjkZAAJKo/1nYmDuwAhHo=,iv:I3mGYoL46KBBxuUe3oES6aCKN41DIQOkIqhhrREIepM=,tag:eYrrfzMltPKMnhPKViEcXQ==,type:str]
            postgresPassword: ENC[AES256_GCM,data:BrbPkF1CW7gaO7n2qn6rI6vVrsw=,iv:BDhY7igCvJBHi6/sIAXdIGemL6ilkK1ar2mGl14Uiqg=,tag:5IHWRWoZLLKgquIxiQcvIA==,type:str]
postgresql:
    auth:
        replicationPassword: ENC[AES256_GCM,data:x9lYOLBGqP++bQ==,iv:uQT0qCBJ5j6Gvp7FDP8D3MahX1g3lzAF4Lt226Bg9bc=,tag:hNhrOobRxOms6G7i+lB/GQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-04T10:44:05Z"
    mac: ENC[AES256_GCM,data:O3RVJdEBsQriA24e+7aMc4c4YloUq4QKWedHcw/g5dSiF3U7EHIZNRGFw5QrYrjz6wZDO6lG6FPfCcAaJZ4LxOlQIsXvMOcoyyCeigYhZ+NoiSCUr6fwkDrHiLZfoev/OkoF89RCF7f49QES9/zoBad55bbi0KTBOFbMha+UtWM=,iv:iO8ptAfsgskNJx4x71bq7uetJg2MsSL3+68/zlxMvdU=,tag:EkUY6hhQTqzeVLM1dITd5Q==,type:str]
    pgp:
        - created_at: "2022-11-04T10:44:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTAQ/+MUQGUFIdhUlMFeivmBNGSA1YEfC/IQWNM+/TA0sd2SwY
            ZWyCNKFlr9cfLrEZT/RxqRR3DmyaGLQrPAAOnirCTAPxmw8L0M5wv+in7Ct/tP7W
            Jz2Du4I0331vQJ06ytRrpSdIQdsGPytq/acGwfiLXMmz738h68QIiQ8V3JlGOqLY
            wy9rSxm1/qJqAQ/kYfsTKPBqqtt2CBoTpbz/Fxp+JnbgSOA3WOlhyjo2ijSZEs1/
            93HXE7A9gZoZgL4HCIBMiXY1VYZV6KxFhKspzgB/wquWWCYS7+rgtA2tvws2geNg
            kgxzws62BFbIVwUiV8VUBjDvqRv7IUKrRgbTtP5/pUB9qgaSUxHLXJx61I0QHbOQ
            iA9IuEaBbgLdAHPW5SUIfCfvrrbubGxLRk0LkMW3eAPyxJ2DxGY9NYtZ+beqlouQ
            U/G1rD3ye/HCwfUyEQjiz5ucjGj1lXlxIKrvdqLgly7MzfUJBOO54KdXWidZIDDL
            E1pM7puwnbmO7+DH2mfvQlfdzTY6nw6tAX2mmn/zSgiLbQ08UyvRkJee6dW2UvGu
            ow+71UcpJJQ2ZWLN8UC5Uoz0dop+6q9xt1zPXxFBRRFUvckfzfIDa7sKvF5cD5G7
            F3Rw3VzcmXmmKUbRy+R4lJ4J8CC7nepBaXwbJKQyiZYbZJTiSNjFasPucr8itl7S
            XgEkhQErQJH2cMe990EvwiiOoT+Lxz0F78Ql5p2Tlw44AfmozzLx8vIhXOXUG2Xo
            FMtGhME9vz/UGeDDSCXUPvbfjOp0/tZPAnWPPTi4Z/K2RoP/eV38sdmiTansDSE=
            =4Vl2
            -----END PGP MESSAGE-----
          fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.7.3
