auth:
    adminUser: ENC[AES256_GCM,data:oHl16zk=,iv:6WNNbzyYch1r43wtwvL47S+uv1M7rjvII2Jgosaqaks=,tag:9j4xqbU9qszqhvPT0Z4uTQ==,type:str]
    adminPassword: ENC[AES256_GCM,data:bIBl0Hf6oX2iS2W+mq9EJuaVI6g=,iv:6MX2WHxQNN/17ivqFO0ApzuGFyT90lAfbsp2Ba2667I=,tag:ywxqc1Vb2jPT+mKWcmDICw==,type:str]
global:
    postgresql:
        auth:
            password: ENC[AES256_GCM,data:FdCdo8yz+Ye21LGyHsz5tsaY5vo=,iv:nAi5ohJ8EjAHNn0lWp3OlQ/ATG8mIQtwqZ5Mrw9ytDU=,tag:PwkLk4TIhvJzDEMA7lZMMA==,type:str]
            postgresPassword: ENC[AES256_GCM,data:H2ONDB5mI3QWFsGTVSCvc8cskcA=,iv:ddTeM9cAYG9ypTqg7AKFoP7Ze2t1IIuJx8ZWR+S/e78=,tag:NrVAIz4C9ZbHUlqbWMwckA==,type:str]
postgresql:
    auth:
        replicationPassword: ENC[AES256_GCM,data:41FESgmk4JQM9w==,iv:GjyPwFi09G0cl+mUAwKudgrWNL2kteYNWoNZkuiLVjg=,tag:hhaKTcSd+05Q7+BjUtC1wQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-28T21:43:04Z"
    mac: ENC[AES256_GCM,data:kmVvgviYcYcOhLGRpvDbH8oEdt23pqgbcUjGBb8ePHfeawjB04g8zfubFbVXbGNVN+TtncP983Pr+nxfpMPqXQPRsO76TpDlIXKfg9JGG+wUV5wAxy/hVKmAh1jAFKRqjiO5UEexvmq0s0e+naR9IyclTkIhaY+g6d6wWfXVj/4=,iv:n8nCVeMj2fhZBnysmZOrbjzaR1fOgRnhEJpTnrpQIro=,tag:gQne8Axf+TlgxxKTcKFDfA==,type:str]
    pgp:
        - created_at: "2024-12-28T21:43:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTAQ/+KNCOH0YEpNbVeODmIaB0hSoaT8Jlnu3nnpCg2POureR+
            c3ePk/MbL1ypI5yhg+JoVhzibhnZ5VPlnQwQhVaHdEN8gzpyV91SjXbRFlA3rvET
            lZwHSefQrGSEm/1eiIZ8baZw7LdIWYUrvda+PIgWPXiK9CiR+eeG5pTPHF8Ku/XG
            VmxBWQsJqvhTOIlfe+rf8phfB4fdDXyMAAFR8ZYn03dIOAkI0vNcYjcLvRsricuU
            j+xlBWWwSjfxg8yv2QFimKi29dZKax21cKctg9F9Lmq3+x6f1hARzFTa6DahC6Ac
            OB+xQwugePn04Anmgl9XEjaEBA925oT8+xTJ048wd1g0yjrwlz0UqW437RZ5PYL3
            lv3Kw0bkKXpC8pNsuO4iNk9pGJ5U6YJoU1Rrrt+EwPmDbrHSAP8K9p/houNvvx6f
            EOF5Voa5wXVb9m/B3NrY17hbD4D7sgI0v72DGLLeSATZfSLsggBo+T8Vl3gmbZiM
            fAA/R+9+FZ7UT6p49OBPJ0erpQk33OQW2lMhLCvxeksnj3r7X69A1SVkt9WQ0eKO
            GAgRSJeeSqZVivb9gCKXlfuPM+whVbn80Cx1OU5n8J3aDtB1khr9PPNXN1kf6VoM
            GHFMKFbbQdGjT9H67M3X1kwEXfrHJO2Xnv7hoVFHoeBFoZCfFoO0G0Ccy5eDwLfS
            XAEchYlurM2Dr4sSFq2jWQ4uIRFEggu7UghLKeqroJbxjTJFli499Ap01VbJEtIU
            /PbIahLx1LfrqGntJNsDW5BDEaddAw48lfuApM+9gK4dVhChSBmapccymTJm
            =tnst
            -----END PGP MESSAGE-----
          fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.9.1
