ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: sonarr.szymonrichert.pl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: sonarr-tls
      hosts:
        - sonarr.szymonrichert.pl

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nas
          operator: In
          values:
          - "true"

podAnnotations:
  oauth2-proxy-admission/secret-name: sonarr-proxy
  oauth2-proxy-admission/secret-namespace: media

resources:
  limits:
    cpu: "2"
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  config:
    enabled: true
    accessMode: ReadWriteMany
    storageClass: nas-nfs
    size: 8Gi
    annotations: {}
  media:
    enabled: true
    type: hostPath
    hostPath: /samba
