ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: sonarr.szymonrichert.pl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: sonarr-tls
      hosts:
        - sonarr.szymonrichert.pl

# podSecurityContext:
#   fsGroup: 1000
#   runAsGroup: 1000
#   # runAsNonRoot: true
#   runAsUser: 1000

resources:
  limits:
    cpu: "2"
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

oauth2proxy:
  clientId: sonarr
  redirectUrl: https://sonarr.szymonrichert.pl/oauth2/callback
  realmUrl: https://auth.szymonrichert.pl/realms/master
  cookieName: oauth2-authorization-cookie
  cookieDomain: sonarr.szymonrichert.pl
  allowedGroups: sonarr

persistence:
  config:
    enabled: true
    storageClass: ceph
    type: pvc
    size: 1Gi
  media:
    enabled: true
    type: hostPath
    hostPath: /samba
