affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - laptop1

# podSecurityContext:
#   fsGroup: 1000

# securityContext:
#   capabilities:
#     drop:
#     - ALL
#   readOnlyRootFilesystem: true
#   runAsNonRoot: true
#   runAsUser: 1000
#   runAsGroup: 1000

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 4
    memory: 4096Mi

persistence:
  documents:
    enabled: true
    type: hostPath
    hostPath: /k8s-data/raid1/documents/
  movies:
    enabled: true
    type: hostPath
    hostPath: /k8s-data/disk/movies
  tvshows:
    enabled: true
    type: hostPath
    hostPath: /k8s-data/disk/tvshows
  music:
    enabled: true
    type: hostPath
    hostPath: /k8s-data/disk/music