installCRDs: true

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 96Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 10m
      memory: 32Mi

cainjector:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 10m
      memory: 128Mi
