repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: kubereboot
  url: https://kubereboot.github.io/charts
- name: cnpg
  url: https://cloudnative-pg.github.io/charts
- name: hashicorp
  url: https://helm.releases.hashicorp.com
- name: ot-helm
  url: https://ot-container-kit.github.io/helm-charts
templates:
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - backbone
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml
  operators-default: &operators
    disableValidation: true
    disableValidationOnInstall: true
    <<: *default
releases:

# - name: vault
#   chart: hashicorp/vault
#   version: 0.28.1
#   namespace: vault
#   labels:
#     purpose: backbone
#     application: vault
#   <<: *default

- name: gha-runner
  chart: oci://ghcr.io/szymonrychu/helm-charts/gha-runner
  version: 2.311.23
  namespace: gha-runner
  labels:
    purpose: backbone
    application: gha-runner
  <<: *default

- name: kured
  chart: kubereboot/kured
  version: 5.6.0
  namespace: kube-system
  labels:
    purpose: backbone
    application: kured
  <<: *default

- name: apt-autoupgrade
  chart: oci://ghcr.io/szymonrychu/helm-charts/ubuntu-apt-autoupgrade
  version: 0.1.0
  namespace: kube-system
  needs:
  - kube-system/kured
  labels:
    purpose: backbone
    application: apt-autoupgrade
  <<: *default

- name: cloudnative-pg
  chart: cnpg/cloudnative-pg
  namespace: postgres-operator
  version: 0.23.0
  force: true
  labels:
    purpose: backbone
    application: cloudnative-pg
  <<: *operators

- name: redis-operator
  chart: ot-helm/redis-operator
  namespace: redis-operator
  version: 0.19.2
  force: true
  labels:
    purpose: backbone
    application: redis-operator
  <<: *operators

# - name: oauth2-proxy-admission-controller
#   chart: oci://ghcr.io/szymonrychu/helm-charts/oauth2-proxy-admission-controller
#   version: 0.1.8
#    namespace: kube-system
#   labels:
#     purpose: backbone
#     application: oauth2-proxy-admission-controller
#   <<: *operators
