repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: kubereboot
  url: https://kubereboot.github.io/charts
- name: szymonrychu
  url: https://szymonrychu.github.io/selfhosted-kubernetes-charts
- name: postgres-operator-charts
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
templates:
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - backbone
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml
  operators-default: &operators
    disableValidation: true
    disableValidationOnInstall: true
    <<: *default
releases:

- name: gha-runner
  chart: szymonrychu/gha-runner
  version: 2.311.0
  namespace: gha-runner
  labels:
    purpose: backbone
    application: gha-runner
  <<: *default

- name: kured
  chart: kubereboot/kured
  version: 5.3.2
  namespace: kube-system
  labels:
    purpose: backbone
    application: kured
  <<: *default

- name: apt-autoupgrade
  chart: szymonrychu/ubuntu-apt-autoupgrade
  version: 0.1.0
  namespace: kube-system
  needs:
  - kube-system/kured
  labels:
    purpose: backbone
    application: apt-autoupgrade
  <<: *default

- name: availability-checker
  chart: szymonrychu/availability-checker
  version: 0.0.3
  namespace: kube-system
  labels:
    purpose: backbone
    application: availability-checker
  <<: *default

- name: postgres-operator
  chart: postgres-operator-charts/postgres-operator
  namespace: postgres-operator
  version: 1.10.1
  force: true
  labels:
    purpose: backbone
    application: postgres-operator
  <<: *operators
