repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: jetstack
  url: https://charts.jetstack.io
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: kubereboot
  url: https://kubereboot.github.io/charts
- name: szymonrychu
  url: https://szymonrychu.github.io/charts
- name: postgres-operator-charts
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
- name: rook-release
  url: https://charts.rook.io/release
- name: csi-driver-smb
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
templates:
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Environment.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml
  operators-default: &operators
    disableValidation: true
    disableValidationOnInstall: true
    <<: *default
releases:

- name: samba
  chart: szymonrychu/samba
  version: 0.2.2
  namespace: samba
  labels:
    purpose: backbone
    application: samba
  <<: *default

- name: csi-driver-smb
  chart: csi-driver-smb/csi-driver-smb
  version: 1.10.0
  namespace: kube-system
  needs:
  - samba/samba
  labels:
    purpose: backbone
    application: smb-csi-driver
  <<: *default

- name: gha-runner
  chart: szymonrychu/gha-runner
  version: 1.0.2
  namespace: gha-runner
  labels:
    purpose: backbone
    application: gha-runner
  <<: *default

- name: kured
  chart: kubereboot/kured
  version: 4.4.1
  namespace: kube-system
  labels:
    purpose: backbone
    application: kured
  <<: *default

- name: apt-autoupgrade
  chart: szymonrychu/ubuntu-apt-autoupgrade
  version: 0.1.0
  namespace: kube-system
  needs:
  - kube-system/kured
  labels:
    purpose: backbone
    application: apt-autoupgrade
  <<: *default

- name: availability-checker
  chart: szymonrychu/availability-checker
  version: 0.0.2
  namespace: kube-system
  labels:
    purpose: backbone
    application: availability-checker
  <<: *default

- name: local-path-provisioner
  chart: szymonrychu/local-path-provisioner
  namespace: rook-ceph
  version: 0.0.24
  labels:
    purpose: storage
    application: local-path-provisioner
  <<: *default

- name: metallb
  chart: szymonrychu/metallb
  namespace: ingress-system
  version: 3.0.12
  labels:
    purpose: backbone
    application: metallb
  <<: *default

- name: cert-manager
  chart: jetstack/cert-manager
  namespace: ingress-system
  version: 1.11.0
  labels:
    purpose: backbone
    application: cert-manager
  <<: *operators

- name: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  namespace: ingress-system
  version: 4.5.2
  needs:
  - ingress-system/metallb
  - ingress-system/cert-manager
  labels:
    purpose: backbone
    application: ingress-nginx
  <<: *default

- name: external-dns
  chart: bitnami/external-dns
  version: 6.13.4
  namespace: ingress-system
  needs:
  - ingress-system/ingress-nginx
  labels:
    purpose: backbone
    application: external-dns
  <<: *default

- name: rook-ceph
  chart: rook-release/rook-ceph
  namespace: rook-ceph
  version: 1.10.11
  labels:
    purpose: backbone
    application: rook-ceph
  <<: *operators

- name: rook-ceph-cluster
  chart: rook-release/rook-ceph-cluster
  namespace: rook-ceph
  version: 1.10.11
  force: true
  labels:
    purpose: backbone
    application: rook-ceph-cluster
  needs:
  - rook-ceph/rook-ceph
  <<: *default

- name: postgres-operator
  chart: postgres-operator-charts/postgres-operator
  namespace: postgres-operator
  version: 1.9.0
  force: true
  labels:
    purpose: backbone
    application: postgres-operator
  <<: *operators
