repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: kubereboot
  url: https://kubereboot.github.io/charts
- name: szymonrychu
  url: https://szymonrychu.github.io/selfhosted-kubernetes-charts
- name: cnpg
  url: https://cloudnative-pg.github.io/charts
templates:
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - backbone
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml
  operators-default: &operators
    disableValidation: true
    disableValidationOnInstall: true
    <<: *default
releases:

- name: gha-runner
  chart: szymonrychu/gha-runner
  version: 2.311.1
  namespace: gha-runner
  labels:
    purpose: backbone
    application: gha-runner
  <<: *default

- name: kured
  chart: kubereboot/kured
  version: 5.5.0
  namespace: kube-system
  labels:
    purpose: backbone
    application: kured
  <<: *default

- name: apt-autoupgrade
  chart: szymonrychu/ubuntu-apt-autoupgrade
  version: 0.1.0
  namespace: kube-system
  needs:
  - kube-system/kured
  labels:
    purpose: backbone
    application: apt-autoupgrade
  <<: *default

- name: cloudnative-pg
  chart: cnpg/cloudnative-pg
  namespace: postgres-operator
  version: 0.21.5
  force: true
  labels:
    purpose: backbone
    application: cloudnative-pg
  <<: *operators

- name: oauth2-proxy-admission-controller
  chart: szymonrychu/oauth2-proxy-admission-controller
  version: 0.1.1
  namespace: kube-system
  labels:
    purpose: backbone
    application: oauth2-proxy-admission-controller
  <<: *operators
