repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: cnpg
  url: https://cloudnative-pg.github.io/charts
templates:
  default: &default
    disableValidation: true
    disableValidationOnInstall: true
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - monitoring
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml

releases:

- name: grafana-database
  chart: cnpg/cluster
  namespace: monitoring
  version: 0.2.0
  force: true
  labels:
    purpose: monitoring
    application: grafana-database
  <<: *default

- name: prometheus
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  version: 67.9.0
  needs:
  - monitoring/grafana-database
  labels:
    purpose: monitoring
    application: prometheus
  <<: *default

- name: smartctl-exporter
  namespace: monitoring
  chart: prometheus-community/prometheus-smartctl-exporter
  version: 0.13.0
  needs:
  - monitoring/prometheus
  labels:
    purpose: monitoring
    application: smartctl-exporter
  <<: *default

- name: microtik-exporter
  namespace: monitoring
  chart: oci://ghcr.io/szymonrychu/helm-charts/microtik-exporter
  version: 0.1.0
  needs:
  - monitoring/prometheus
  labels:
    purpose: monitoring
    application: microtik-exporter
  <<: *default

- name: loki
  namespace: monitoring
  chart: grafana/loki-stack
  version: 2.10.2
  labels:
    purpose: monitoring
    application: loki
  needs:
  - monitoring/prometheus
  <<: *default
