repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: loki
  url: https://grafana.github.io/loki/charts
templates:
  default: &default
    disableValidation: true
    disableValidationOnInstall: true
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Environment.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml

releases:

- name: prometheus
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  version: 39.12.1
  labels:
    purpose: monitoring
    application: prometheus
  <<: *default

- name: loki
  namespace: monitoring
  chart: loki/loki-stack
  version: 2.1.2
  labels:
    purpose: monitoring
    application: loki
  needs:
  - monitoring/prometheus
  <<: *default
