apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: keycloak-postgresql
#  labels:
#    application: test-app
#    environment: demo
#  annotations:
#    "acid.zalan.do/controller": "second-operator"
#    "delete-date": "2020-08-31"  # can only be deleted on that day if "delete-date "key is configured
#    "delete-clustername": "acid-test-cluster"  # can only be deleted when name matches if "delete-clustername" key is configured
spec:
  dockerImage: ghcr.io/zalando/spilo-15:2.1-p9
  teamId: keycloak
  numberOfInstances: 1
  users:  # Application/Robot users
    superuser:
    - superuser
    - createdb
    keycloak: []
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  enableConnectionPooler: false # enable/disable connection pooler deployment
  enableReplicaConnectionPooler: false # set to enable connectionPooler for replica service
  allowedSourceRanges:  # load balancers' source ranges for both master and replica services
  - 127.0.0.1/32
  databases:
    keycloak: keycloak
  postgresql:
    version: "14"
    parameters:  # Expert section
      shared_buffers: "32MB"
      max_connections: "60"
      log_statement: "all"
#  env:
#  - name: wal_s3_bucket
#    value: my-custom-bucket

  volume:
    size: 5Gi
    storageClass: local-path

  enableShmVolume: true
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi

  enableLogicalBackup: false
  # logicalBackupSchedule: "30 00 * * *"

  maintenanceWindows:
    - 01:00-06:00  #UTC
    - Sat:00:00-04:00
