---
redisStandalone:
  name: paperless-ngx-redis
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  namespace: monitoring

redisExporter:
  enabled: true
  image: quay.io/opstree/redis-exporter
  # renovate: image=quay.io/opstree/redis-exporter
  tag: "v1.44.0"
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: ceph
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 5Gi

podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000
