ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
  hosts:
    - host: paperless-ngx.szymonrichert.pl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: paperless-ngx-tls
      hosts:
        - paperless-ngx.szymonrichert.pl

gotenbergTika:
  enabled: true

paperless_url: https://paperless-ngx.szymonrichert.pl

redis:
  host: paperless-ngx-redis

database:
  host: paperless-ngx-database-cluster-rw
  name: paperless-ngx
  usernameSecret: paperless-ngx-database-cluster-app/username
  passwordSecret: paperless-ngx-database-cluster-app/password

podSecurityContext:
  fsGroup: 1000

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 750m
    memory: 1Gi

persistence:
  data:
    enabled: true
    accessMode: ReadWriteMany
    storageClass: ceph
    size: 20Gi
    annotations: {}
  media:
    enabled: true
    type: hostPath
    hostPath: /samba/documents/paperless/media
  export:
    enabled: true
    type: hostPath
    hostPath: /samba/documents/paperless/export
  consume:
    enabled: true
    accessMode: ReadWriteMany
    storageClass: ceph
    size: 20Gi
    annotations: {}
