oauth2proxy:
    config:
        clientSecret: ENC[AES256_GCM,data:8xY1xyGOxd4p1VxnoB6aWQpMGOZok/uwefRucAxBD9Y=,iv:UMZ9PjhxmvZsP/Ts23YzOfO8178PRvBv2RCnWGZRHnA=,tag:MP5sgmvRmHIiw+esKwwbRw==,type:str]
        cookieSecret: ENC[AES256_GCM,data:6bLa93E8U0eK3gAPZCFNFQ==,iv:mgvXCEAwyxjir9lx3UsaU0V1klLEBKVDzcXAz7dnkks=,tag:M/XLqgdcW3bhQlkDk7KF6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-02T11:29:17Z"
    mac: ENC[AES256_GCM,data:G0yIiVQYpIwweL0GkarqGvVrmzWIcavqwOTDjzzuFzK6sDYkfM9Lu2q4Yip2V2gaCn6Ljw4O8MfwBwk3f4GmFBeUTff433GTrNyEzu1VKJZbmUB2q4zkA28lyFsvulR3JT1SzCOnff1Ux3TizVP0NDnfv9v/6j0CVc5sOp3ss4Q=,iv:UfJVDBnsWv67+57CEZ036qEBhrNFhYtQ1zGTkZtBsfA=,tag:ngA9s8mJYz4iH/td0Nfx9Q==,type:str]
    pgp:
        - created_at: "2024-02-02T11:29:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTAQ/8DQS5M43UffaMZqvs0dedc0/hByaXUaYtrx+pl9S80MDd
            4Sz8tjri2XCvH4mUgiGgkZO9ugi1bAJvSba85Zl3TAFZ+4BZUbdx4tjLOcWVO7sP
            s10I6AGSoZ2Kiv/812nITTx6zn2HCBkMF9H6kOE0/HQWUMl+NqsvZaYMTtk0cD2Q
            UQTkGwZVeJ6e3au8+24LmTUWBynqbsA8XDsN3AOsQqrfF64t3dLimdXUFuP28EbT
            DjMTbx0n5hw1ntPpA8JC1jxl7RrfXFc8YiV6UCaE9RdKAv3fAYHw0WnY5zXgh1gd
            0xbpUUKrytbiyyCtbdGMAm6vDRsyUhV/4kHCeADAKT7KsmJaJw1dDxAlXB772l31
            042aHkAjv9TXT+I4Z3yTO1yV+AsZhPIKc1puiHc6Q5vN2uq9Q4y2Od3wxiy9/geP
            HdvPsS4SHnPH1hywZBrMRgXWTLbO2jU15iq12xMtzd6MttC1m8tzIMqKZE4k3Gox
            4xPHwilHe3CSo+m4KtfRhWHMAiF9GcYNXhYdSlQ3VwpMgoXbuidIRbINwMuCyHBc
            A3GAor+CnS3ApwTKPa2w+BEdQtBZbsdsiADblQmkRtEKHy9bgIBg7T+//DOpbJ7N
            MyyKWMjWLxUIs58zhRvcuBb262ZJzcJcuKg/XF0eplrxywisjTB0lPqTyJj3GQXS
            XgFJZ3r9Zb3MzwJW6taQK2aSX0PJYnAMY2F6fC3H8ALTLJMjs2PxbUaUz2FnarrJ
            bf7uO9viToBKTao3ep5TLxQqmvO/hzAKenGWmMPN2czXSbYnjtWuBlR81sr4mpA=
            =yvUo
            -----END PGP MESSAGE-----
          fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.7.3
