version:
  postgresql: "15"

cluster:
  instances: 3
  storage:
    size: 50Gi
    storageClass: ceph
  walStorage:
    enabled: true
    size: 10Gi
    storageClass: ceph
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  priorityClassName: system-cluster-critical

  # -- Affinity/Anti-affinity rules for Pods
  # See: https://cloudnative-pg.io/documentation/current/cloudnative-pg.v1/#postgresql-cnpg-io-v1-AffinityConfiguration
  affinity:
    topologyKey: kubernetes.io/hostname

  monitoring:
    enabled: true
    podMonitor:
      enabled: true
    prometheusRule:
      enabled: false
    customQueries:
      - name: "pg_cache_hit_ratio"
        query: "SELECT current_database() as datname, sum(heap_blks_hit) / (sum(heap_blks_hit) + sum(heap_blks_read)) as ratio FROM pg_statio_user_tables;"
        metrics:
          - datname:
              usage: "LABEL"
              description: "Name of the database"
          - ratio:
              usage: GAUGE
              description: "Cache hit ratio"

  initdb:
    database: grafana
    owner: grafana


backups:
  enabled: true
  s3:
    region: eu-central-1
    bucket: database-backup-szymonrychu
    path: /grafana-database/
