---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: block-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rook-ceph-nuc1
  namespace: storage-system
spec:
  capacity:
    storage: 230Gi
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: block-storage
  local:
    path: /dev/disk/by-id/ata-SSD_256GB_YS202305231545HT
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nuc1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rook-ceph-nuc2
  namespace: storage-system
spec:
  capacity:
    storage: 230Gi
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: block-storage
  local:
    path: /dev/disk/by-id/ata-Patriot_P210_256GB_P210IIBB23102405152
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nuc2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rook-ceph-nuc3
  namespace: storage-system
spec:
  capacity:
    storage: 230Gi
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: block-storage
  local:
    path: /dev/disk/by-id/ata-SSD_256GB_YS202305232763HT
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nuc3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rook-ceph-nuc4
  namespace: storage-system
spec:
  capacity:
    storage: 230Gi
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: block-storage
  local:
    path: /dev/disk/by-id/ata-Patriot_P210_256GB_P210JBCB23100601928
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nuc4
