initContainers:
  custom-webui:
    name: custom-webui
    image: curlimages/curl:7.76.1
    command:
    - "/bin/sh"
    - "-c"
    - "curl -o- -sL https://github.com/johman10/flood-for-transmission/releases/download/latest/flood-for-transmission.tar.gz | tar xzf - -C /config"
    volumeMounts:
    - name: config
      mountPath: /config
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000


affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - laptop1

env:
  TZ: UTC
  TRANSMISSION_WEB_HOME: /web
  TRANSMISSION_RPC_PASSWORD: "*oik4sahx9EeKae5!"
  TRANSMISSION_DOWNLOAD_DIR: /downloads/transmission-complete
  TRANSMISSION_INCOMPLETE_DIR_ENABLED: false
  TRANSMISSION_INCOMPLETE_DIR: /downloads/transmission-incomplete
  TRANSMISSION_WATCH_DIR_ENABLED: false
  TRANSMISSION_WATCH_DIR: /watch

ingress:
  main:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: transmission.szymonrichert.pl
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: transmission-tls
        hosts:
          - transmission.szymonrichert.pl

service:
  main:
    ports:
      http:
        port: 4180
        targetPort: 4180

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: false
  runAsUser: 1000

hostNetwork: false
# dnsPolicy: "None"
# dnsConfig:
#   nameservers:
#     - 8.8.8.8
#     - 1.1.1.1

resources:
  limits:
    cpu: 250m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  config:
    enabled: true
    storageClass: local-path
    type: pvc
    mountPath: /config
    retain: true
    size: 10Gi
  downloads:
    enabled: true
    type: hostPath
    mountPath: /downloads
    hostPath: /k8s-data/disk
