---
# handlers file for openvpn

- name: Restart Consul
  ansible.builtin.service:
    name: consul
    state: restarted
    enabled: yes
  when:
    - not ansible_check_mode | bool

- name: Restart Consul Template
  ansible.builtin.service:
    name: consul-template
    state: restarted
    enabled: yes
  when:
    - not ansible_check_mode | bool

- name: Restart Systemd Resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
    enabled: yes
  when:
    - not ansible_check_mode | bool
