repositories:
- name: ot-helm
  url: https://ot-container-kit.github.io/helm-charts

templates:
  operators-default:
    disableValidation: true
    disableValidationOnInstall: true
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - media
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml

releases:

- name: qbittorrent
  chart: oci://ghcr.io/szymonrychu/helm-charts/qbittorrent
  version: 2.1.4
  namespace: media
  labels:
    purpose: media
    application: qbittorrent
  <<: *default

- name: sonarr
  chart: oci://ghcr.io/szymonrychu/helm-charts/sonarr
  version: 2.0.1
  namespace: media
  labels:
    purpose: media
    application: sonarr
  <<: *default

- name: radarr
  chart: oci://ghcr.io/szymonrychu/helm-charts/radarr
  version: 2.0.1
  namespace: media
  labels:
    purpose: media
    application: radarr
  <<: *default

- name: lidarr
  chart: oci://ghcr.io/szymonrychu/helm-charts/lidarr
  version: 0.0.1
  namespace: media
  labels:
    purpose: media
    application: lidarr
  <<: *default

- name: prowlarr
  chart: oci://ghcr.io/szymonrychu/helm-charts/prowlarr
  version: 1.0.1
  namespace: media
  labels:
    purpose: media
    application: prowlarr
  <<: *default

- name: bazarr
  chart: oci://ghcr.io/szymonrychu/helm-charts/bazarr
  version: 1.0.2
  namespace: media
  labels:
    purpose: media
    application: bazarr
  <<: *default

- name: filebrowser
  chart: oci://ghcr.io/szymonrychu/helm-charts/filebrowser
  version: 2.0.4
  namespace: media
  labels:
    purpose: media
    application: filebrowser
  <<: *default

- name: jellyfin
  chart: oci://ghcr.io/szymonrychu/helm-charts/jellyfin
  version: 0.6.11
  namespace: media
  labels:
    purpose: media
    application: jellyfin
  <<: *default

- name: jellyseer
  chart: oci://ghcr.io/szymonrychu/helm-charts/jellyseerr
  version: 0.0.8
  namespace: media
  labels:
    purpose: media
    application: jellyseer
  <<: *default

- name: unmanic
  chart: oci://ghcr.io/szymonrychu/helm-charts/unmanic
  version: 0.1.3
  namespace: media
  labels:
    purpose: media
    application: unmanic
  <<: *default

# - name: paperless-ngx-redis
#   chart: ot-helm/redis
#   namespace: paperless-ngx
#   version: 0.16.4
#   force: true
#   labels:
#     purpose: media
#     application: paperless-ngx-redis
#   <<: *default

# - name: paperless-ngx-database
#   chart: cnpg/cluster
#   namespace: paperless-ngx
#   version: 0.0.11
#   force: true
#   labels:
#     purpose: media
#     application: paperless-ngx-database
#   <<: *default

# - name: paperless-ngx
#   chart: oci://ghcr.io/szymonrychu/helm-charts/paperless-ngx
#   version: 0.1.6
#   namespace: paperless-ngx
#   labels:
#     purpose: media
#     application: paperless-ngx
#   needs:
#     - paperless-ngx/paperless-ngx-redis
#     - paperless-ngx/paperless-ngx-database
#   <<: *default

# - name: bitmagnet-database
#   chart: cnpg/cluster
#   namespace: media
#   version: 0.0.11
#   force: true
#   labels:
#     purpose: media
#     application: bitmagnet-database
#   <<: *default

# - name: bitmagnet
#   chart: oci://ghcr.io/szymonrychu/helm-charts/bitmagnet
#   version: 0.0.1
#   namespace: media
#   labels:
#     purpose: media
#     application: bitmagnet
#   needs:
#     - media/bitmagnet-database
#   <<: *default
