repositories:
- name: szymonrychu
  url: https://szymonrychu.github.io/selfhosted-kubernetes-charts
templates:
  operators-default:
    disableValidation: true
    disableValidationOnInstall: true
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - media
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml

releases:

- name: qbittorrent
  # chart: szymonrychu/qbittorrent
  # version: 0.0.1
  chart: ../../../selfhosted-kubernetes-charts/charts/qbittorrent
  namespace: media
  labels:
    purpose: media
    application: qbittorrent
  <<: *default


  # "qbittorrent_client_id": {
  #   "sensitive": true,
  #   "type": "string",
  #   "value": "qbittorrent"
  # },
  # "qbittorrent_client_secret": {
  #   "sensitive": true,
  #   "type": "string",
  #   "value": "5mBIfUMV7thDQOjgVcXbXmnr0Cgz5A7g"
  # }
