repositories:
- name: szymonrychu
  url: https://szymonrychu.github.io/selfhosted-kubernetes-charts
templates:
  operators-default:
    disableValidation: true
    disableValidationOnInstall: true
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - media
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml

releases:

- name: qbittorrent
  chart: szymonrychu/qbittorrent
  version: 1.0.2
  namespace: media
  labels:
    purpose: media
    application: qbittorrent
  <<: *default

- name: sonarr
  chart: szymonrychu/sonarr
  version: 1.0.4
  namespace: media
  labels:
    purpose: media
    application: sonarr
  <<: *default

- name: radarr
  chart: szymonrychu/radarr
  version: 1.0.3
  namespace: media
  labels:
    purpose: media
    application: radarr
  <<: *default

- name: prowlarr
  chart: szymonrychu/prowlarr
  version: 0.0.4
  namespace: media
  labels:
    purpose: media
    application: prowlarr
  <<: *default

- name: jackett
  chart: szymonrychu/jackett
  version: 1.0.3
  namespace: media
  labels:
    purpose: media
    application: jackett
  <<: *default

- name: filebrowser
  chart: szymonrychu/filebrowser-oauth2
  version: 1.0.1
  namespace: media
  labels:
    purpose: media
    application: filebrowser
  <<: *default

- name: jellyfin
  chart: szymonrychu/jellyfin
  version: 0.6.0
  namespace: media
  labels:
    purpose: media
    application: jellyfin
  <<: *default
