ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: qbt.szymonrichert.pl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: qbt-tls
      hosts:
        - qbt.szymonrichert.pl


qbittorrent:
  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000

oauth2Proxy:
  enabled: false
  keycloakClientId: qbittorrent
  keycloakRedirectmUrl: https://qbt.szymonrichert.pl/oauth2/callback
  keycloakRealmUrl: https://auth.szymonrichert.pl/realms/lab
  cookieName: oauth2-authorization-cookie
  cookieDomain: qbt.szymonrichert.pl
  allowedGroups: qbittorrent
  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000

initPermissions:
  enabled: true
  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsUser: 1000
    # runAsGroup: 1000

persistence:
  - name: config
    enabled: true
    storageClass: nas-nfs
    type: pvc
    mountPath: /config
    size: 10Gi
  - name: media
    enabled: true
    type: hostPath
    mountPath: /downloads
    hostPath: /data


portal:
  enabled: true
