ingress:
  main:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: qbt.szymonrichert.pl
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: qbt-tls
        hosts:
          - qbt.szymonrichert.pl

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  # runAsNonRoot: true
  runAsUser: 1000

persistence:
  config:
    enabled: true
    storageClass: local-path
    type: pvc
    mountPath: /config
    retain: true
    size: 10Gi
  movies:
    enabled: true
    type: hostPath
    mountPath: /media/movies
    hostPath: /k8s-data/disk/movies
  tvshows:
    enabled: true
    type: hostPath
    mountPath: /media/tvshows
    hostPath: /k8s-data/disk/tvshows
  music:
    enabled: true
    type: hostPath
    mountPath: /media/music
    hostPath: /k8s-data/disk/music


portal:
  enabled: true
