ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: qbt.szymonrichert.pl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: qbt-tls
      hosts:
        - qbt.szymonrichert.pl

podAnnotations:
  oauth2-proxy-admission/secret-name: qbittorrent-proxy
  oauth2-proxy-admission/secret-namespace: media

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  # runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    cpu: "1"
    # memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  config:
    enabled: true
    storageClass: ceph
    type: pvc
    size: 10Gi
  media:
    enabled: true
    type: hostPath
    hostPath: /samba
