oauth2proxy:
    clientSecret: ENC[AES256_GCM,data:QmS6C8hH2dUlkJV8yLbWv5l+0F138NDB06DycfJZzSc=,iv:xzWVFtpqNvTju2Y7PrVlktMeAuz2oRY8qzdeX+WVflo=,tag:PDPR9fmruWkhDPZazaO2aQ==,type:str]
    cookieSecret: ENC[AES256_GCM,data:B6j1Ni2ZztDCkKcyBKlHxQ==,iv:Lq9BviRbhMalj41aPlcLGG1xYC4FMxZEmQkdl8ienmw=,tag:bGnvTfwaXzVcAYlAF/oTsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-21T08:13:09Z"
    mac: ENC[AES256_GCM,data:Nixk6RBDA8Yla2r+ec5SRHhIHZ3EqwCU67Ijv64xu1F0DQjRS3jd3xH+DBDJLw35pQrWJ3xl8IFXQv+FYZ9OA1JtG6WdTmik8zaOhu+28S21c2kGhRa2ZV7FwydEN93gO2NaxqznqzgvA+KPx3ivAfVzMVSOGK1ZgiNTyK83IEo=,iv:yx3h5WqzvdxHCQHwzJLHGxJKiXWizvs4PFHW1JDTgOE=,tag:EANhQgWxOVA5Dn/0s0oU1A==,type:str]
    pgp:
        - created_at: "2024-03-21T08:13:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTAQ/9FbvgbiAbWi/IoCFRjftdyk23ESFBTK28tUjvc1TCJ2GZ
            EWX9LD1DOgCoxEGpS0IRS4K1elOvJ918HwcZDcVxQb0JCYpeADhhKpx2D9ch65nT
            30Va+Q9+JeC3xpoZjqOuVq4epoproVSppxrn2t3Mh1gfnQk5fz1pcvEXrASsUQDe
            6HmrxdhtCLpKLpi3zC7mUp+oj79WieJQEcUIHWzHEGCm+uCNPFaW7lTLvU5KxXOo
            C2ee8NGsEzCd7SzNWCJvzKRGIQ2LXEile1lWAt3Pz9kwU1F7+34lVkxm8DkeHn7E
            nKJZrvOW7dhpEB92Uv4Uzxp3P+pVUIIHk9fPjjzFz4BMZJKBr2wfPiSbhsB/Y1De
            vvAs2jBU7YS0QtuY/wHfD6EVX6eMHTlHZh8BIwpvfoALinefdpFqKVfdLtwmm1QZ
            Ep9JByni9HOPz7b/cuBGPcACsoRZRe2mCIrxi5KO4Bya5P46+fm3QJ6xpc+UPPqO
            Jybg2XgI0yZ+NGDn9q+pvU2P6gZ5BEksAnKhXL2KGVFA2pNqfi/jppte06KIGyKi
            tMFYZRUXtKjPxftukCUYqnoQoYRcmU0rP/bHoklxruxQL3uCDzLRiSzwiCqWT59J
            UkY21pvjCDYr+jTxGOkK4ua6qDClJvd8AcXx3/dZYn0iwrl5viCCfMhooo54xZfS
            XgGcUik5++n+N3i1txjrv24zyEbAUphzVBdqFYNmq2ExhtJHuW5HEXA0eEHMgOzc
            Qyy1YOimk6qo5BSdY1phmWz4/c+O1rqaadB7AWmU6E7qD1dVWrEE6dTgGAl0JwU=
            =ZoOU
            -----END PGP MESSAGE-----
          fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.7.3
