---
k3s_installer_version: 1.24
k3s_k8s_version: v1.24.6
first_k3s_master_node: node1

k8s_master_nodes: []
k8s_worker_nodes: []

k8s_api_cert_sans:
  - 10.8.0.16
  - 10.8.0.17
  - 10.8.0.18
  - 192.168.1.16
  - 192.168.1.17
  - 192.168.1.18
  - szymonrichert.pl
  - k8s.szymonrichert.pl

k3s_install_log_path: /var/log/k3s.log
k3s_node_iface: eno1
k3s_token: token