templates:
  default: &default
    disableValidation: true
    disableValidationOnInstall: true
    wait: true
    missingFileHandler: Warn
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - monitoring
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml

releases:

- name: code-server
  version: 2.2.8
  timeout: 2400
  chart: oci://ghcr.io/szymonrychu/helm-charts/code-server
  namespace: code-server
  labels:
    purpose: editor
    application: code-server
  <<: *default
