repositories:
- name: szymonrychu
  url: https://szymonrychu.github.io/selfhosted-kubernetes-charts
- name: harbor
  url: https://helm.goharbor.io
- name: cnpg
  url: https://cloudnative-pg.github.io/charts
templates:
  default: &default
    disableValidation: true
    disableValidationOnInstall: true
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - monitoring
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml

releases:

- name: code-server
  version: 2.0.0
  chart: szymonrychu/code-server
  namespace: code-server
  labels:
    purpose: editor
    application: code-server
  <<: *default

- name: harbor-database
  chart: cnpg/cluster
  namespace: harbor
  version: 0.0.11
  force: true
  labels:
    purpose: coding
    application: harbor-database
  <<: *default

- name: harbor
  version: 1.15.1
  chart: harbor/harbor
  namespace: harbor
  needs:
  - harbor/harbor-database
  labels:
    purpose: coding
    application: harbor
  <<: *default
