ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 20g
  hosts:
    - host: files.szymonrichert.pl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: files-tls
      hosts:
        - files.szymonrichert.pl

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nas
          operator: In
          values:
          - "true"

podAnnotations:
  oauth2-proxy-admission/secret-name: files-proxy
  oauth2-proxy-admission/secret-namespace: media

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  # runAsNonRoot: true
  runAsUser: 1000

# resources:
#   limits:
#     cpu: "2"
#     memory: 1024Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

persistence:
  config:
    enabled: true
    storageClass: nas-nfs
    type: pvc
    size: 1Gi
  media:
    enabled: true
    type: hostPath
    hostPath: /samba
