oauth2proxy:
    clientSecret: ENC[AES256_GCM,data:znFxBTMdKA7E0Y4tnc31DlIWi2MOD/8x7FLo4gIWzTk=,iv:XHl2CG6Y33IgJ7Eu4eJYqlA1HXYv6dRYp2c91I+lED4=,tag:vBebtKuozPiu/Ke1wYswnA==,type:str]
    cookieSecret: ENC[AES256_GCM,data:eyIF0WoTPYv37kijImrqOg==,iv:MJ60qXVUTGF9EGk+hUf/Gkdx28jSRTxcToy12G7SDSA=,tag:JGO0CeB+vxCrfVl7dIFSfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-15T07:57:11Z"
    mac: ENC[AES256_GCM,data:kel0n8pcUKPkgwme6xCmjl1lInIeyqq0zWpQ7bdaRcuUwI86TEBLBk6csM6pxO5BSJK1XHRU3CT5fXgK9VBblGm4jsXlK7pbEXEzt1omEwq8Chr+aTBhPKbem6oO3PnZGYiKrPBH4CRc/ZZBtf04dq08J8Ixftjc02Dy1Rj4sYg=,iv:Y9QtATCxUKpoGzg16mUpjynAsc9z9bOzaDgBY+F5OQc=,tag:69NMseB1mwFrmq9iJnkzeg==,type:str]
    pgp:
        - created_at: "2024-02-15T07:57:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTARAAor2NBS9zefmLSi6qjyVtRGp3pfg5D4q24EeDwJZnxcdG
            MBBg+QHfJ/u0Fkjt+mMGCvdKa8ksvuDui9HR0dnNhCGlG8BOAcsCav2Cvz8gkJN6
            lKAZQfBdMMTJscMY4KaSFXIdu+miIKYVEon/TvMKNRZheYRmUMCPANX3kkliUBFR
            O3E2lJeTWHIdoNdfKN4STrN0OUEsWG0xFX37FUZ7w1J9KPGTQtKgIFhAUGRb6cPD
            ZkcQsvdYoYISSHSry8H3K+NbjmEJ/XZ4NB3IXFx0Bef7v2/9EKKAF+5OYSsjQVKi
            nJ9aN3XV/ztShcC01B3H/D/ad0ztkQ5YBN0jgHTpC4oIFNmOzYynKq5gHY5Kvpdw
            0QYsVli6O76prJ8sVjiZq5NhyeQea1xPW0sv6sr+fIb2fbHbKYBvHTVaG3NJNKpi
            Gj5DKlAPc3BXYRE0pAG5n+cUp/sKUXkfVvL2Zj1dWNZBtuvmeO7lS7fDoGteGo24
            EbYu0Vs/dGMdnCYLGVZJuEB5XZNFvdhnjZ0wEPqC9r0eJrE9gHnif+8WF3Il3Gx9
            I+vTnuFDehV0Yfoicn8NHNT4q5tfxE1Vn6MxrC5++tQB+AvWTedB07f0/DcMfxGA
            o+cAobXyK53SWagRG1KDFgdRan4x3HEL8YYQ5cqWSGcFOSV4Cx9cOvcmQP54XJLS
            XgHtEvzZVjoIO9JLjMHCAeXc6zR+UXRjfQI0iOLFjDvT3wt0xjChw46BaX1NzrYo
            rpymsazPJeaANJngYn+KNY0Ekwj1SdNpnJWdtfQHJ3flNwdMklnzA/U7VeRcmCw=
            =21Id
            -----END PGP MESSAGE-----
          fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.7.3
