hub:
    config:
        GenericOAuthenticator:
            client_id: ENC[AES256_GCM,data:xwGWolN86dQuIg==,iv:6wkvTsuGfg8+n3Xumurzg/qH8AlHxcyY9w1yFrzzP38=,tag:7O5q7ohSFYH/zOtQOCcebg==,type:str]
            client_secret: ENC[AES256_GCM,data:yq0QEm9j80o/H6npiDFQ80xDX9BW9OdSwdGyahk8PfA=,iv:MXdN4Fe+33d1YGHkwkNQIEY6QFOHxfiMi8DXgA+91HY=,tag:rYfcV4SL8JBVn+rguBibzA==,type:str]
    db:
        url: ENC[AES256_GCM,data:Nr57nibL1mPQS88v4joi3ZDORP3ca+SZvAocNXn+39iYxDP++TzaxGH3xjMspacDYp6FdqHdFTSktY4k6I4NZeH3kV9y7sGyUe920zTMFMfErb5GF8gkF96cC5JnsfME5NPWJbhwSjCUnAh6vN48aSAYv4CnwbzONbwMGcT7lXm4XzkCCNdW,iv:pGAW5OLOX6IIPgNWuECRmsbCQtYTFkM2Rqs7Tp8pCZY=,tag:Pn5OWM+pRsqFSqmHWv7gZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-04T19:41:20Z"
    mac: ENC[AES256_GCM,data:gajkPdgespQKRxh1Ap0BcILbi9pBuBXzbqE4Dlh5WKBrIrtzSKdX4R6ZqUucW4HT9C68nWDNFbjnijDJJf3yDOji+nz5BUmqlt72GH9AofW4bY4kp0Y9ZOgCIuGiV5dINv92Y1X7qNMJuZRN7ndFNzyfHj4OLmbuShpHy8gPlFw=,iv:LYfUR/bofWRzUPawlVSMxpcQK7bbKe3nnHkXgbeBrNI=,tag:qGNeVRwrcJvosLc0/yfxkA==,type:str]
    pgp:
        - created_at: "2023-09-04T19:41:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTAQ//Xgm6Bmp/uNO4XD9w+rYpgmjhbRPl1oXoE9eQnCMLNo4c
            XyvEYK/d8X8mmYxRZ4t6LzwO/wP9RLCv2PwPn1+ZaM9U5mEyM/anJm/W4sncVSiO
            7ESuaDXF2kxpULUOV8AkFLOhpAqhFRgV71iNFBYA0Yb3thbbhT5QK/uuYJ9nVmFl
            rRqsp0xV6uw0tREOi/I5fiNm6O+nekn+9VdZjxLUfIGv0R4T8+93c9LV8buB8YBh
            C02Fm5wqLRnL91winf4skQFVqhzLOg6bbZDVagJFMKTRQMlilKMr6OdlYwCI8cEL
            xVvZ8vddBEYmzLscxVVdyBr+NkZVKaXu80xom+KFOSf2jxjArX8lF+DD21PTgkAM
            3QSOdlTOopy4iJQQZ/F6ldsscfetcyh/1UO5Y8Q5NPSxgZguGukIPznkw/2l0U02
            nY83RqpD0H85k74hWk6MJTQUimxqHh13qv5L2IFEDYOI6r/8RiWZ7fdrS1Q5HMvJ
            j2pLIT+rLV3B61c058Cxv6muStCmq2qKQP3yX4raTUXiAzDPwxE6msQFluNQtp+I
            FrdxI0mmF9kelOeWXM1DCEPxijpMj7+IrZuMqPjGRdsAVQePMutnWm1Zwjjx/RFg
            unx7k7G4Hn59k8LBwFjYYf334WWacYao0lYpNNsMi2jogriZ8vyo1lL5BfPNsDnS
            XgGiukSWaq5awm+WCGKGqS1N9Uwi9TOvcuTk4B9GZwKEXER176W7EgV4+g7OBCYk
            6bHLoqyvNBsTINFikyXcoFJMmHBuTshI6/rgvWjX5pUabgMa/GGfxTVrn1FztmE=
            =vRm/
            -----END PGP MESSAGE-----
          fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.7.3
