ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
  hosts:
    - host: bitmagnet.szymonrichert.pl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: bitmagnet-tls
      hosts:
        - bitmagnet.szymonrichert.pl

podAnnotations:
  oauth2-proxy-admission/secret-name: bitmagnet-proxy
  oauth2-proxy-admission/secret-namespace: media

database:
  host: bitmagnet-database-cluster-rw
  name: bitmagnet
  usernameSecret: bitmagnet-database-cluster-app/username
  passwordSecret: bitmagnet-database-cluster-app/password

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 750m
    memory: 1Gi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nuc1
          - nuc2
          - nuc3
          - nuc4

