repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
templates:
  default: &default
    wait: true
    missingFileHandler: Warn
    timeout: 600
    hooks:
    - events:
      - prepare
      - presync
      - postsync
      showlogs: true
      command: ../../.hook.sh
      args:
      - storage
      - '{{`{{ .Event.Name }}`}}'
      - '{{`{{ .Release.Name }}`}}'
      - '{{`{{ .Release.Namespace }}`}}'
    values:
    - values/common.yaml
    - values/{{`{{ .Environment.Name }}`}}.yaml
    - values/{{`{{ .Release.Name }}`}}/common.yaml
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - values/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.secrets.yaml
  operators-default:
    disableValidation: true
    disableValidationOnInstall: true
    <<: *default
releases:

- name: wordpress
  version: 16.1.25
  chart: bitnami/wordpress
  namespace: blog
  labels:
    purpose: blog
    application: wordpress
  <<: *default
