
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: dperson/samba
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See [image docs](https://github.com/dperson/samba/blob/master/README.md) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  SHARE1: movies;/media/movies;yes;no;no
  SHARE2: tvshows;/media/tvshows;yes;no;no
  SHARE3: music;/media/music;yes;no;no
  SHARE4: public;/media/documents;yes;no;no
  NMDP: yes
  RECYCLE: yes
  PERMISSIONS: 644:644
  GLOBAL1: tls enabled=no
  GLOBAL2: bind interfaces only = yes

hostNetwork: true

podSecurityContext:
  fsGroup: 1000
  # runAsGroup: 1000
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    enabled: false

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nuc1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml

persistence:
  movies:
    enabled: true
    type: hostPath
    mountPath: /media/movies
    hostPath: /k8s-data/disk/movies
  tvshows:
    enabled: true
    type: hostPath
    mountPath: /media/tvshows
    hostPath: /k8s-data/disk/tvshows
  music:
    enabled: true
    type: hostPath
    mountPath: /media/music
    hostPath: /k8s-data/disk/music


