ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: bazarr.szymonrichert.pl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: bazarr-tls
      hosts:
        - bazarr.szymonrichert.pl

resources:
  limits:
    cpu: "2"
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

oauth2proxy:
  clientId: bazarr
  redirectUrl: https://bazarr.szymonrichert.pl/oauth2/callback
  realmUrl: https://auth.szymonrichert.pl/realms/master
  cookieName: oauth2-authorization-cookie
  cookieDomain: bazarr.szymonrichert.pl
  allowedGroups: bazarr

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /var/lib/bazarr
  media:
    enabled: true
    type: hostPath
    hostPath: /samba
