oauth2proxy:
    clientSecret: ENC[AES256_GCM,data:PFngp7HmUxxWnViwrbsc4prypFOlDJCSXDmo2KK19IA=,iv:cdQVSNZPEvaVJ5E6XIgqCRTB/alHksPj1MbaS+JPhE8=,tag:DDy31V0Xr4r+C6zHrluuVQ==,type:str]
    cookieSecret: ENC[AES256_GCM,data:512rxI2Ul4d1dX5AUhrxjQ==,iv:2Kpjo1ffc2NM6v8CbpvB1V3fgoumJWrjV6xrDdYpsks=,tag:T9/RW3hteLuW3eq8VhcAkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-05T16:59:11Z"
    mac: ENC[AES256_GCM,data:1ZmTc3dirTVBQSZE6DjsMr98kEWNiaRFteeM8CRGAJh7W++AmGZQy631AJDCAt4ywS2q40MghtGXo4h2mTmB0gyNqxHeWTCB+X/qnCg6xraScgno3Brj4ierh2W+Dtnp0wl+UlO9BmjCL765XIHHOqk4Oi44J2iYWZSpTyQI+0Q=,iv:4pFSImT6SQpDSWej/kJiHVtGZMQ9eJZVW+2K/T4xYOM=,tag:sg35z6vI22rXYB0SC0rGxQ==,type:str]
    pgp:
        - created_at: "2024-05-05T16:59:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTARAAwtEesLcgBbk3pS0yP91ZbmJJIYtv8o7TK1ThvTlqQUio
            DseQa9mJ1LE6VHCCDkTmij0cG1C8+HBGjCE2+q/qqKTEitU76i5x7E+5WFLRav/d
            TQM0y2CwDONdWQFMV0B4IimMrO/ytZuAiMhlARktr5+1vtL6fhrFjZnSLUSX5Q90
            ul8ejS/0qOXIBLUIj85b9OP2sdZjylSqx7hLv25xQNfd+82lBynujQeE6+VAQ4l+
            n3bjk3jXYaXMUFSYfFv4Po1jdec2wya5lxS6/kSFvPfq9vhltoGm0o8kb413dAYK
            SWbxihQ9ef8za+j1TBU7rns1N3GCpQMvqoAvpTczKjr3clywdsa8ZjxO59f0Zw3Z
            Ncz+kaqe2r7f6NavVtE/CtdCUMJMAPsmTvZY339gVTS7CUnMV7ZVMMs26kQ6yh5k
            D8k91OwY1DRjHjcv+0WGO9mycHbBkMd02ZRPgaH5JoLkp4QmZ483McDlENqn8S7h
            upQzwFxg8w4gxbLxHx4jER8kvaSlRCf3lFfmi8hs7Pb4EugTv8Ujho5UgBZZOOY8
            mQzpRzm3D1VI5BdvbYQ9Ks5NyeR+OU+wGGKRT1fBeVRPQ+Nvaops0n7ZiUEp3mYJ
            cal/2+FbdJjBH7pWSYCbqNSADawcXTyZ32Oc9VERcZrPTvaQpHQQamsY3w5J1wXS
            XgGUj4rG+EEnTN/BSWPdLRnxGsmVpRwp38qUJvjdAxamoukUDKzsi4XcKkpcN7yM
            61fzGhA+6TvOoqfL+rjwWt75lTGzm1+Bbmg83lj74HR6t7GBI6cOWk73FxNqXrI=
            =7hkQ
            -----END PGP MESSAGE-----
          fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.7.3
