ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
  hosts:
    - host: jellyfin.szymonrichert.pl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: jellyfin-tls
      hosts:
        - jellyfin.szymonrichert.pl

nvidiaVisibleDevice: GPU-2e5cba96-e2d4-57ca-8b12-7652194abf17

securityContext:
  privileged: true

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  # runAsNonRoot: true
  runAsUser: 1000
  supplementalGroups:
    - 109

# hostNetwork: true

resources:
  requests:
    cpu: 200m
    memory: 256Mi
    gpu.intel.com/i915: 1
  limits:
    cpu: "8"
    memory: 12Gi
    gpu.intel.com/i915: 1

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /var/lib/jellyfin
  media:
    enabled: true
    type: hostPath
    hostPath: /samba
