ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: jellyfin.szymonrichert.pl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: jellyfin-tls
      hosts:
        - jellyfin.szymonrichert.pl

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - laptop1

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 4
    memory: 4096Mi

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /k8s-data/jellyfin-config
  movies:
    enabled: true
    type: hostPath
    hostPath: /k8s-data/disk/movies
  tvshows:
    enabled: true
    type: hostPath
    hostPath: /k8s-data/disk/tvshows
  music:
    enabled: true
    type: hostPath
    hostPath: /k8s-data/disk/music