
config:
  localVoiceProcessing:
    enabled: true
    whisperModel: small-int8
    whisperBeamSize: 8
  network:
    trustedProxies:
      - 0.0.0.0/0
  postgresql:
    enabled: false
  prometheus:
    enabled: true

podSecurityContext:
  fsGroup: 1000

priorityClassName:
  homeassistant: system-cluster-critical

securityContexts:
  # homeassistant:
  #   capabilities:
  #     drop:
  #     - ALL
  #   runAsUser: 1000
  #   runAsGroup: 1000
  #   runAsNonRoot: true
  piper:
    capabilities:
      drop:
      - ALL
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  whisper:
    capabilities:
      drop:
      - ALL
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  openwakeword:
    capabilities:
      drop:
      - ALL
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  initJinjaRenderer:
    capabilities:
      drop:
      - ALL
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  initWaitForPostgres:
    capabilities:
      drop:
      - ALL
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true

initWaitForPostgres:
  enabled: true
  host: home-assistant-postgresql

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: home-assistant.szymonrichert.pl
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: home-assistant-tls
      hosts:
        - home-assistant.szymonrichert.pl

resources:
  homeassistant:
    requests:
      cpu: 10m
      memory: 320Mi
    limits:
      cpu: 500m
      memory: 1Gi
  openwakeword:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Gi
  piper:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Gi
  whisper:
    requests:
      cpu: 10m
      memory: 396Mi
    limits:
      cpu: 500m
      memory: 512Gi
  initJinjaRenderer:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
  initWaitForPostgres:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

persistence:
  homeassistant:
    enabled: true
    storageClass: ceph
    accessMode: ReadWriteMany
    size: 50Gi
  piper:
    enabled: true
    storageClass: ceph
    accessMode: ReadWriteMany
    size: 8Gi
  whisper:
    enabled: true
    storageClass: ceph
    accessMode: ReadWriteMany
    size: 8Gi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "kubernetes.io/hostname"
          operator: In
          values:
            - nuc1
            - nuc2
            - nuc3
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/instance
          operator: In
          values:
          - home-assistant-influxdb
      topologyKey: "kubernetes.io/hostname"

zalandoPostgresql:
  enabled: false
  persistence:
    size: 20Gi
    storageClass: ceph
