
config:
  network:
    trustedProxies:
      - 0.0.0.0/0

podSecurityContext:
  fsGroup: 1000

containerSecurityContext:
  capabilities:
    drop:
    - ALL
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true

initSecurityContext:
  capabilities:
    drop:
    - ALL
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true

initWaitForPostgres:
  enabled: true
  host: home-assistant-postgresql

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: home-assistant.szymonrichert.pl
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: home-assistant-tls
      hosts:
        - home-assistant.szymonrichert.pl

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 10m
    memory: 320Mi

initResources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  storageClass: nas-nfs
  accessMode: ReadWriteMany
  size: 8Gi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "kubernetes.io/hostname"
          operator: In
          values:
            - nuc1
            - nuc2
            - nuc3
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/instance
          operator: In
          values:
          - home-assistant-influxdb
      topologyKey: "kubernetes.io/hostname"

influxdb:
  enabled: false
  setDefaultUser:
    enabled: true
    user:
      username: "admin"
      password:
  resources:
    requests:
      memory: 256Mi
      cpu: 10m
    limits:
      memory: 512Mi
      cpu: 250m

  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
              - nuc1
              - nuc2
              - nuc3
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - home-assistant-influxdb
        topologyKey: "kubernetes.io/hostname"
    
  securityContext:
    enabled: true
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  persistence:
    enabled: true
    storageClass: nas-nfs
    accessModes: 
      - ReadWriteMany

zalandoPostgresql:
  enabled: true