ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: unmanic.szymonrichert.pl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: unmanic-tls
      hosts:
        - unmanic.szymonrichert.pl

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nas
          operator: In
          values:
          - "true"

image:
  tag: 0.2.7

securityContext:
  privileged: true

podAnnotations:
  oauth2-proxy-admission/secret-name: unmanic-proxy
  oauth2-proxy-admission/secret-namespace: media

podSecurityContext:
  fsGroup: 1000
  # runAsNonRoot: true
  supplementalGroups:
    - 109

# hostNetwork: true

resources:
  requests:
    cpu: 200m
    memory: 256Mi
    gpu.intel.com/i915: 1
  limits:
    cpu: "8"
    memory: 12Gi
    gpu.intel.com/i915: 1

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /var/lib/unmanic
  media:
    enabled: true
    type: hostPath
    hostPath: /samba
  cache:
    enabled: true
    type: hostPath
    hostPath: /samba/.unmanic_cache
