
auth:
  username: home-assistant
  database: home-assistant
architecture: replication # standalone
primary:
  podSecurityContext:
    enabled: true
    fsGroup: 1000
  containerSecurityContext:
    enabled: true
    runAsUser: 1000
    runAsNonRoot: true
  podLabels:
    application: postgresql-primary
  persistence:
    enabled: true
    storageClass: local-path
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
              - nuc1
              - nuc2
              - nuc3
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: application
            operator: In
            values:
            - postgresql-primary
        topologyKey: "kubernetes.io/hostname"
  resources:
    requests:
      memory: 64Mi
      cpu: 10m
    limits:
      memory: 256Mi
      cpu: 100m
readReplicas:
  replicaCount: 3
  podSecurityContext:
    enabled: true
    fsGroup: 1000
  containerSecurityContext:
    enabled: true
    runAsUser: 1000
    runAsNonRoot: true
  podLabels:
    application: postgresql-readonly
  persistence:
    enabled: true
    storageClass: local-path
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
              - nuc1
              - nuc2
              - nuc3
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: application
            operator: In
            values:
            - postgresql-readonly
        topologyKey: "kubernetes.io/hostname"
  resources:
    requests:
      memory: 64Mi
      cpu: 10m
    limits:
      memory: 256Mi
      cpu: 100m
