configInline:
  address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 178.183.206.26/32

controller:
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 32Mi

speaker:
  secretValue: dCks9hsEoP9WP82Pv3pC8xxjzENAm0qrIevcmqwjyC4fBo2d9cKtdYElkTh6BaycUUEE0EeVqw6YWry9OIjmF74rZMV0SMVhKbqWoDk0iHKGDOIQO5SJXZLzNFiNxrYKnaNJ0vlyO84iMYCn7kC4ff4su4TulsKSUXOEzvmXWTXSWIVEMFLRT3E0I8RR3k5WZ9UTuYIb0BbR5E9GPNsleZFKlu6s9VbrgPelVnY6lZ5YAgGhMtsCzEFn8SVIAAao
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 32Mi