ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: esphome.szymonrichert.pl
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: esphome-tls
      hosts:
        - esphome.szymonrichert.pl

podAnnotations:
  oauth2-proxy-admission/secret-name: esphome-proxy
  oauth2-proxy-admission/secret-namespace: home-automation

securityContext:
  privileged: true
  # runAsUser: 1000
  # runAsGroup: 1000
  # runAsNonRoot: true

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  # limits:
  #   cpu: 500m
  #   memory: 512Mi


persistence:
  enabled: true
  storageClass: ceph
  accessMode: ReadWriteMany
  size: 8Gi
