ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: esphome.szymonrichert.pl
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: esphome-tls
      hosts:
        - esphome.szymonrichert.pl


oauth2proxy:
  clientId: esphome
  redirectUrl: https://esphome.szymonrichert.pl/oauth2/callback
  realmUrl: https://auth.szymonrichert.pl/realms/master
  cookieName: oauth2-authorization-cookie
  cookieDomain: esphome.szymonrichert.pl
  allowedGrous: esphome

# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - laptop1


securityContext:
  privileged: true
  # runAsUser: 1000
  # runAsGroup: 1000
  # runAsNonRoot: true

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  # limits:
  #   cpu: 500m
  #   memory: 512Mi


persistence:
  enabled: true
  storageClass: ceph
  accessMode: ReadWriteMany
  size: 8Gi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "kubernetes.io/hostname"
          operator: In
          values:
            - nuc1
            - nuc2
            - nuc3
