ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: esphome.szymonrichert.pl
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: esphome-tls
      hosts:
        - esphome.szymonrichert.pl



# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - laptop1

# podSecurityContext:
#   fsGroup: 1000

# containerSecurityContext:
#   capabilities:
#     drop:
#     - ALL
#   enabled: true
#   runAsUser: 1000
#   runAsNonRoot: true

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 10m
    memory: 320Mi


persistence:
  enabled: true
  storageClass: nas-nfs
  accessMode: ReadWriteMany
  size: 8Gi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "kubernetes.io/hostname"
          operator: In
          values:
            - nuc1
            - nuc2
            - nuc3