---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  type: ExternalName
  externalName: 192.168.1.72
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: media
spec:
  ingressClassName: nginx
  rules:
  - host: jellyfin.szymonrichert.pl
    http:
      paths:
      - backend:
          service:
            name: plex
            port:
              number: 8096
        path: /
        pathType: Prefix
