---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  type: ExternalName
  externalName: 192.168.1.32
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: media
spec:
  ingressClassName: nginx
  rules:
  - host: plex.szymonrichert.pl
    http:
      paths:
      - backend:
          service:
            name: plex
            port:
              number: 32400
        path: /
        pathType: Prefix
  # tls:
  # - hosts:
  #   - plex.szymonrichert.pl
  #   secretName: qbt-tls
