---
  
- name: "Setup OpenVPN server"
  ansible.builtin.include_tasks:
    file: server.yml
  when: vpn_master_hostname == inventory_hostname

- name: "Setup OpenVPN clients"
  ansible.builtin.include_tasks:
    file: client.yml
  when: vpn_master_hostname != inventory_hostname
