persistence:
    imageChartStorage:
        s3:
            accesskey: ENC[AES256_GCM,data:fimIR8usnoQTK44q0ZUECa02xWQ=,iv:dcj62m/Po0zJBgHgTino5FpXdU1IJsgy0GHSBPqyf5k=,tag:uTZg20upkITvogPWUG8bwQ==,type:str]
            secretkey: ENC[AES256_GCM,data:nSTHTzCXlkAY1s6Y0mzHzb+WkiJGfAA2S4UjLFvRi4mrAPYvG9ruzA==,iv:P1D4Jn3Qk0rZL8AXNBwj0gSkf5q3XkGrBy/7TMyKuOI=,tag:z/gSFOhNIRuxsVLacZH2nA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-09T20:52:30Z"
    mac: ENC[AES256_GCM,data:pmeSQDIpUeTj1JGF1SIbUgsSR1lcU5y8Vk/7zPMAkOSkq1VFMNO/R0t9aezhYI3BROJfDWBwmHPIAEcqhwv+VZXlXJ8ok9d61h+05dniQu9wbJE4PNIoeiY08o7e8iyuwmvcum3NQMA8JOidPv9qikDt5ySUg5vQDzlMFTF8ybc=,iv:S8nNQfFqsdB5NdVmREVHqpcDiTPFkQUXkbfHHo1Nz0g=,tag:eAXGINzQUZFSfkWo2QTzKA==,type:str]
    pgp:
        - created_at: "2024-09-09T20:52:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTAQ/6Aryz3zimgyIdVnoBqCs5rPxoekmowipIEKHlBE9yl7ZM
            cGRTQEuMqW5b7CMwykMv+LtejARtOUp5H6Q9dt0iXgcS8XVHv1fTcjKJ/jrLbcKK
            jA7bHwiLrG+ubJoGwkJ3Xv+hkqyobKfgkXfJzz3YLqMmpvVkOgllXtK6KS3yXe2W
            P+Do5upBKkIcySL7393p3fBpGjoSzQ/F5vwjC3kVAlmC2OLqBCQupHcDYdssrpis
            NDtOK8WsqQ92H6HvuK3o9/RNuU8Pg2/RLjxEyKQROfodY01Ed3neiuIdPurxulo5
            9j2vNUcSq/exefqFH50nzfAqXHvFRAdwrshQ062uGph8i/+aO654tZOFAAvl/dm+
            WUEQuUqqRe5e0egBwW+KURnjtmp9Iz5FSloHzmg4MjjZ39nzDGVrr4WeJa5T+jud
            HO4iesQWu4lRH9KbLD8o1buP81MiohnhEN8OSyUK57Cibo4mawLVlgI5XrQmAer2
            ihP9CnYe5k7ExlYoHt4MtGRn2PBGnxY5p3eimA+x8X/JlvDd8TOWH+nvot0Bzltb
            B4iVsrx6XeLOl5BVYAV16P+mssbMKV8mkDtQI9a61UBbPeGVpthNmk0DVqBqIMsh
            YmVA8Lmdxae3fzdblEwbJKivKMxykt/aHsvUR6QFGwm9r1ajzZiJ4tvV3vUIdqPS
            XgGlh9QJk3HPPs/f4ujTjPNuKkBTBmgD1iFy/0ztvTuiegTP3u+MCqpFnc6UNZPq
            ixkv1/B3gc73NRlz3YoAF2NxaqN8ecC9t+EahsL34L33ZJK+oz/eNfT1qynvUrg=
            =uO7L
            -----END PGP MESSAGE-----
          fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.9.0
