# name: autoupgrade

# on:
#   schedule:
#     - cron:  '0 8 * * 1,2,3,4,5' # 10:00 UTC -> 12:00 Warsaw at Saturdays

# env:
#   BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
#   BOT_EMAIL: "szymon.rychu@gmail.com"
#   BOT_USERNAME: "szymonrychu"

# jobs:
#   build:
#     runs-on: [self-hosted, linux, X64]
#     steps:

#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Refresh central repo
#       run: |
#         set -e
#         rm -rf /tmp/central-repo
        
#         git clone https://x-access-token:${BOT_TOKEN}@github.com/szymonrychu/helmfile-cluster.git /tmp/central-repo
#         cd /tmp/central-repo
        
#         ./autoupgrader.py

#         git config --global user.email "${BOT_EMAIL}"
#         git config --global user.name "${BOT_USERNAME}"

#         (git add -A && git commit -m "Daily autoupgrade external charts" && git push origin master) || true
