name: diff

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Helmfile Diff
    runs-on: [self-hosted, linux, X64]
    steps:

    - name: Checkout code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      with:
        repository: szymonrychu/helmfile-cluster
        token: ${{ secrets.BOT_TOKEN }}
        submodules: recursive

    - name: Diff
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        set -e
        echo $ENCRYPTION_KEY | base64 --decode > encryption_key.gpg
        gpg --import encryption_key.gpg
        helmfile diff || true
