name: Helmfile Diff

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Helmfile Diff
    runs-on: [self-hosted, linux, X64]
    steps:
    
    - name: Turnstyle
      if: github.ref == 'refs/heads/main'
      uses: softprops/turnstyle@8db075d65b19bf94e6e8687b504db69938dc3c65 # v1
      with:
        continue-after-seconds: 1200
        poll-interval-seconds: 60
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        repository: szymonrychu/helmfile-cluster
        token: ${{ secrets.BOT_TOKEN }}
        submodules: recursive

    - name: Diff
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        set -e
        echo $ENCRYPTION_KEY | base64 --decode > encryption_key.gpg
        gpg --import encryption_key.gpg
        helmfile diff || true
