name: Helmfile Diff

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Helmfile Diff
    runs-on: [self-hosted, linux, X64]
    steps:

    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        repository: szymonrychu/helmfile-cluster
        token: ${{ secrets.BOT_TOKEN }}
        submodules: recursive

    - name: Diff
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        set -e
        echo $ENCRYPTION_KEY | base64 --decode > encryption_key.gpg
        gpg --import encryption_key.gpg
        helmfile diff || true
