name: Helmfile Apply

on:
  push:
    branches:
      - main
  release:
    types:
      - created
  schedule:
    - cron: "0 9 * * 0,1,2,3,4"
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}

jobs:
  build:
    runs-on: [self-hosted, linux, X64]
    steps:
    
    - name: Turnstyle
      if: github.ref == 'refs/heads/main'
      uses: softprops/turnstyle@8db075d65b19bf94e6e8687b504db69938dc3c65 # v1
      with:
        continue-after-seconds: 180
        poll-interval-seconds: 10
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        repository: szymonrychu/helmfile-cluster
        token: ${{ secrets.BOT_TOKEN }}
        submodules: recursive

    - name: Sync
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        set -e
        echo $ENCRYPTION_KEY | base64 --decode > encryption_key.gpg
        gpg --import encryption_key.gpg
        helmfile apply
