name: Helmfile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}

env:
  TERRAFORM_VERSION: 1.8.2

jobs:
  terraform:
    runs-on: [self-hosted, linux, X64]
    name: Terraform
    steps:
      # - name: Setup terraform
      #   run: |
      #     wget -qO /tmp/terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      #     unzip -u -d /tmp/ /tmp/terraform.zip
      #     sudo mv /tmp/terraform /usr/local/bin/terraform
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          token: "${{ secrets.SZYMONRYCHU_TOKEN }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform init
        env:
          TERRAFORM_TFVARS: ${{ secrets.TERRAFORM_TFVARS }}
        run: |
          cd terraform
          echo "${TERRAFORM_TFVARS}" | base64 --decode > terraform.tfvars
          terraform init

      - name: Terraform plan
        if: github.ref != 'refs/heads/main'
        run: |
          cd terraform
          terraform plan -lock-timeout=600s

      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd terraform
          terraform apply -auto-approve -lock-timeout=600s

  list_changed_releases:
    runs-on: ubuntu-latest
    needs: terraform
    name: List changed releases
    outputs:
      changed_releases: ${{ steps.changed_releases.outputs.changed_releases }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          token: "${{ secrets.SZYMONRYCHU_TOKEN }}"

      - name: Get all test, doc and src files that have changed
        id: changed_files
        uses: tj-actions/changed-files@bab30c2299617f6615ec02a68b9a40d10bd21366 # v45
        with:
          json: true
          escape_json: false

      - name: Filter release names
        id: changed_releases
        run: |
          ./.github/get_changed_releases.py '${{ steps.changed_files.outputs.all_changed_files }}' >> "$GITHUB_OUTPUT"

  build:
    runs-on: [self-hosted, linux, X64]
    name: ${{ matrix.helmfile_label }}
    needs: list_changed_releases
    if: needs.list_changed_releases.outputs.changed_releases != '[]'
    strategy:
      fail-fast: true
      matrix:
        helmfile_label: ${{ fromJson(needs.list_changed_releases.outputs.changed_releases) }}
    steps:

    - name: Turnstyle
      if: github.ref == 'refs/heads/main'
      uses: softprops/turnstyle@ab8b8426f6b6562c0ff7f220433860183338596c # v2
      with:
        continue-after-seconds: 1200
        poll-interval-seconds: 60
      env:
        GITHUB_TOKEN: ${{ secrets.SZYMONRYCHU_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        token: "${{ secrets.SZYMONRYCHU_TOKEN }}"

    - name: Login to GHCR szymonrychu
      run: |
        echo "${{ secrets.SZYMONRYCHU_TOKEN }}" | helm registry login -u szymonrychu --password-stdin ghcr.io

    - name: helmfile diff
      if: github.ref != 'refs/heads/main'
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        set -e
        echo $ENCRYPTION_KEY | base64 --decode > encryption_key.gpg
        gpg --import encryption_key.gpg
        helmfile --selector ${{ matrix.helmfile_label }} diff --include-needs

    - name: helmfile apply
      if: github.ref == 'refs/heads/main'
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        set -e
        echo $ENCRYPTION_KEY | base64 --decode > encryption_key.gpg
        gpg --import encryption_key.gpg
        helmfile --selector ${{ matrix.helmfile_label }} apply --include-needs

  helmfile_completed:
    needs: [build]
    name: Helmfile Completed
    runs-on: ubuntu-latest
    steps:
      - name: complete message
        run: echo "Completed"
