name: sync

on:
  push:
    branches:
      - main
  release:
    types:
      - created

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, linux, X64]
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: szymonrychu/helmfile-cluster
        token: ${{ secrets.BOT_TOKEN }}
        submodules: recursive

    - name: Sync
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        set -e
        echo $ENCRYPTION_KEY | base64 --decode > encryption_key.gpg
        gpg --import encryption_key.gpg
        helmfile apply
