name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1-5"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.SZYMONRYCHU_BOT_TOKEN }}
      - name: Renovate
        uses: renovatebot/github-action@757597d1bb6993c6406e207997a85f2b20ff39be # v41.0.4
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.SZYMONRYCHU_BOT_TOKEN }}
        env:
          RENOVATE_AUTOMERGE: true
