name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1-5"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: ${{ secrets.SZYMONRYCHU_BOT_TOKEN }}
      - name: Renovate
        uses: renovatebot/github-action@64257ea9bae8d8634eba1d545638c2cab62e69e6 # v39.2.1
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.SZYMONRYCHU_BOT_TOKEN }}
        env:
          RENOVATE_AUTOMERGE: true
