name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 0,1,2,3,4"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
      - name: Renovate
        uses: renovatebot/github-action@c56dbeca772b331ddf18eefad8b93f0f3c69d34a # v34.159.2
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_AUTOMERGE: true