name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 0,1,2,3,4"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
      - name: Renovate
        uses: renovatebot/github-action@39e2c46b45e5f435a422aa850d5288a35a2341d4 # v34.63.2
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_AUTOMERGE: true