name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1-5"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          token: ${{ secrets.SZYMONRYCHU_BOT_TOKEN }}
      - name: Renovate
        uses: renovatebot/github-action@7743ec9e19ceeb61a3862c5d4131e6710195af11 # v40.3.3
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.SZYMONRYCHU_BOT_TOKEN }}
        env:
          RENOVATE_AUTOMERGE: true
