name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1-5"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ secrets.SZYMONRYCHU_BOT_TOKEN }}
      - name: Renovate
        uses: renovatebot/github-action@b266b24b144602ed4f512f0773009d026722f4cc # v40.2.6
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.SZYMONRYCHU_BOT_TOKEN }}
        env:
          RENOVATE_AUTOMERGE: true
